// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_strm_dout,
        w_strm_empty_n,
        w_strm_read,
        w_strm_num_data_valid,
        w_strm_fifo_cap,
        h,
        g,
        f,
        e,
        d,
        c,
        b,
        a,
        add_ln6888_out,
        add_ln6888_out_ap_vld,
        add_ln6897_out,
        add_ln6897_out_ap_vld,
        add_ln6906_out,
        add_ln6906_out_ap_vld,
        add_ln6915_out,
        add_ln6915_out_ap_vld,
        add_ln6924_out,
        add_ln6924_out_ap_vld,
        add_ln6933_out,
        add_ln6933_out_ap_vld,
        add_ln6942_out,
        add_ln6942_out_ap_vld,
        add_ln6951_out,
        add_ln6951_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] w_strm_dout;
input   w_strm_empty_n;
output   w_strm_read;
input  [5:0] w_strm_num_data_valid;
input  [5:0] w_strm_fifo_cap;
input  [31:0] h;
input  [31:0] g;
input  [31:0] f;
input  [31:0] e;
input  [31:0] d;
input  [31:0] c;
input  [31:0] b;
input  [31:0] a;
output  [31:0] add_ln6888_out;
output   add_ln6888_out_ap_vld;
output  [31:0] add_ln6897_out;
output   add_ln6897_out_ap_vld;
output  [31:0] add_ln6906_out;
output   add_ln6906_out_ap_vld;
output  [31:0] add_ln6915_out;
output   add_ln6915_out_ap_vld;
output  [31:0] add_ln6924_out;
output   add_ln6924_out_ap_vld;
output  [31:0] add_ln6933_out;
output   add_ln6933_out_ap_vld;
output  [31:0] add_ln6942_out;
output   add_ln6942_out_ap_vld;
output  [31:0] add_ln6951_out;
output   add_ln6951_out_ap_vld;

reg ap_idle;
reg w_strm_read;
reg add_ln6888_out_ap_vld;
reg add_ln6897_out_ap_vld;
reg add_ln6906_out_ap_vld;
reg add_ln6915_out_ap_vld;
reg add_ln6924_out_ap_vld;
reg add_ln6933_out_ap_vld;
reg add_ln6942_out_ap_vld;
reg add_ln6951_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln682_reg_1479;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln682_fu_609_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    w_strm_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln682_reg_1479_pp0_iter1_reg;
wire   [5:0] trunc_ln600_fu_621_p1;
reg   [5:0] trunc_ln600_reg_1483;
reg   [5:0] trunc_ln600_reg_1483_pp0_iter1_reg;
reg   [31:0] Wt_reg_1488;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [31:0] a_2_fu_896_p2;
reg   [31:0] a_2_reg_1493;
reg    ap_condition_exit_pp0_iter2_stage0;
reg   [6:0] t_fu_374;
wire   [6:0] t_2_fu_615_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_t_1;
wire    ap_block_pp0_stage0;
reg   [31:0] c_1_fu_378;
wire    ap_block_pp0_stage0_grp0;
reg   [31:0] d_1_fu_382;
reg   [31:0] g_1_fu_386;
reg   [31:0] h_1_fu_390;
reg   [31:0] Kt_fu_394;
wire   [31:0] Kt_1_fu_902_p131;
reg   [31:0] add_ln6951_fu_398;
wire   [31:0] add_ln695_fu_1195_p2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [31:0] add_ln6942_fu_402;
wire   [31:0] add_ln694_fu_1190_p2;
reg   [31:0] add_ln6933_fu_406;
wire   [31:0] add_ln693_fu_1185_p2;
reg   [31:0] add_ln6924_fu_410;
wire   [31:0] add_ln692_fu_1180_p2;
reg   [31:0] add_ln6915_fu_414;
wire   [31:0] add_ln691_fu_1175_p2;
reg   [31:0] add_ln6906_fu_418;
wire   [31:0] add_ln690_fu_1170_p2;
reg   [31:0] add_ln6897_fu_422;
wire   [31:0] add_ln689_fu_1165_p2;
reg   [31:0] add_ln6888_fu_426;
wire   [31:0] add_ln688_fu_1280_p2;
reg   [31:0] b_1_fu_430;
reg   [31:0] d_2_fu_434;
reg   [31:0] f_1_fu_438;
wire   [31:0] e_2_fu_824_p2;
reg   [31:0] h_2_fu_442;
wire    ap_block_pp0_stage0_01001_grp0;
wire   [5:0] trunc_ln580_fu_667_p1;
wire   [25:0] lshr_ln_fu_657_p4;
wire   [10:0] trunc_ln580_1_fu_681_p1;
wire   [20:0] lshr_ln580_1_fu_671_p4;
wire   [31:0] xor_ln580_fu_699_p2;
wire   [24:0] trunc_ln580_2_fu_695_p1;
wire   [6:0] lshr_ln580_2_fu_685_p4;
wire   [31:0] and_ln580_fu_721_p2;
wire   [31:0] and_ln580_1_fu_727_p2;
wire   [31:0] or_ln580_1_fu_713_p3;
wire   [31:0] or_ln580_2_fu_733_p3;
wire   [31:0] xor_ln580_2_fu_747_p2;
wire   [31:0] or_ln_fu_705_p3;
wire   [31:0] add_ln580_1_fu_759_p2;
wire   [31:0] xor_ln580_3_fu_753_p2;
wire   [31:0] xor_ln580_1_fu_741_p2;
wire   [31:0] add_ln580_fu_771_p2;
wire   [31:0] add_ln580_2_fu_765_p2;
wire   [31:0] T1_fu_776_p2;
wire   [31:0] xor_ln591_fu_830_p2;
wire   [1:0] trunc_ln581_fu_792_p1;
wire   [29:0] lshr_ln1_fu_782_p4;
wire   [12:0] trunc_ln581_1_fu_806_p1;
wire   [18:0] lshr_ln581_1_fu_796_p4;
wire   [31:0] and_ln591_fu_836_p2;
wire   [31:0] and_ln591_1_fu_842_p2;
wire   [21:0] trunc_ln581_2_fu_820_p1;
wire   [9:0] lshr_ln581_2_fu_810_p4;
wire   [31:0] or_ln591_1_fu_856_p3;
wire   [31:0] or_ln591_2_fu_870_p3;
wire   [31:0] xor_ln591_2_fu_878_p2;
wire   [31:0] or_ln1_fu_848_p3;
wire   [31:0] xor_ln591_1_fu_864_p2;
wire   [31:0] add_ln591_fu_890_p2;
wire   [31:0] xor_ln591_3_fu_884_p2;
wire   [31:0] Kt_1_fu_902_p129;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] Kt_1_fu_902_p1;
wire   [5:0] Kt_1_fu_902_p3;
wire   [5:0] Kt_1_fu_902_p5;
wire   [5:0] Kt_1_fu_902_p7;
wire   [5:0] Kt_1_fu_902_p9;
wire   [5:0] Kt_1_fu_902_p11;
wire   [5:0] Kt_1_fu_902_p13;
wire   [5:0] Kt_1_fu_902_p15;
wire   [5:0] Kt_1_fu_902_p17;
wire   [5:0] Kt_1_fu_902_p19;
wire   [5:0] Kt_1_fu_902_p21;
wire   [5:0] Kt_1_fu_902_p23;
wire   [5:0] Kt_1_fu_902_p25;
wire   [5:0] Kt_1_fu_902_p27;
wire   [5:0] Kt_1_fu_902_p29;
wire   [5:0] Kt_1_fu_902_p31;
wire   [5:0] Kt_1_fu_902_p33;
wire   [5:0] Kt_1_fu_902_p35;
wire   [5:0] Kt_1_fu_902_p37;
wire   [5:0] Kt_1_fu_902_p39;
wire   [5:0] Kt_1_fu_902_p41;
wire   [5:0] Kt_1_fu_902_p43;
wire   [5:0] Kt_1_fu_902_p45;
wire   [5:0] Kt_1_fu_902_p47;
wire   [5:0] Kt_1_fu_902_p49;
wire   [5:0] Kt_1_fu_902_p51;
wire   [5:0] Kt_1_fu_902_p53;
wire   [5:0] Kt_1_fu_902_p55;
wire   [5:0] Kt_1_fu_902_p57;
wire   [5:0] Kt_1_fu_902_p59;
wire   [5:0] Kt_1_fu_902_p61;
wire   [5:0] Kt_1_fu_902_p63;
wire  signed [5:0] Kt_1_fu_902_p65;
wire  signed [5:0] Kt_1_fu_902_p67;
wire  signed [5:0] Kt_1_fu_902_p69;
wire  signed [5:0] Kt_1_fu_902_p71;
wire  signed [5:0] Kt_1_fu_902_p73;
wire  signed [5:0] Kt_1_fu_902_p75;
wire  signed [5:0] Kt_1_fu_902_p77;
wire  signed [5:0] Kt_1_fu_902_p79;
wire  signed [5:0] Kt_1_fu_902_p81;
wire  signed [5:0] Kt_1_fu_902_p83;
wire  signed [5:0] Kt_1_fu_902_p85;
wire  signed [5:0] Kt_1_fu_902_p87;
wire  signed [5:0] Kt_1_fu_902_p89;
wire  signed [5:0] Kt_1_fu_902_p91;
wire  signed [5:0] Kt_1_fu_902_p93;
wire  signed [5:0] Kt_1_fu_902_p95;
wire  signed [5:0] Kt_1_fu_902_p97;
wire  signed [5:0] Kt_1_fu_902_p99;
wire  signed [5:0] Kt_1_fu_902_p101;
wire  signed [5:0] Kt_1_fu_902_p103;
wire  signed [5:0] Kt_1_fu_902_p105;
wire  signed [5:0] Kt_1_fu_902_p107;
wire  signed [5:0] Kt_1_fu_902_p109;
wire  signed [5:0] Kt_1_fu_902_p111;
wire  signed [5:0] Kt_1_fu_902_p113;
wire  signed [5:0] Kt_1_fu_902_p115;
wire  signed [5:0] Kt_1_fu_902_p117;
wire  signed [5:0] Kt_1_fu_902_p119;
wire  signed [5:0] Kt_1_fu_902_p121;
wire  signed [5:0] Kt_1_fu_902_p123;
wire  signed [5:0] Kt_1_fu_902_p125;
wire  signed [5:0] Kt_1_fu_902_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 t_fu_374 = 7'd0;
#0 c_1_fu_378 = 32'd0;
#0 d_1_fu_382 = 32'd0;
#0 g_1_fu_386 = 32'd0;
#0 h_1_fu_390 = 32'd0;
#0 Kt_fu_394 = 32'd0;
#0 add_ln6951_fu_398 = 32'd0;
#0 add_ln6942_fu_402 = 32'd0;
#0 add_ln6933_fu_406 = 32'd0;
#0 add_ln6924_fu_410 = 32'd0;
#0 add_ln6915_fu_414 = 32'd0;
#0 add_ln6906_fu_418 = 32'd0;
#0 add_ln6897_fu_422 = 32'd0;
#0 add_ln6888_fu_426 = 32'd0;
#0 b_1_fu_430 = 32'd0;
#0 d_2_fu_434 = 32'd0;
#0 f_1_fu_438 = 32'd0;
#0 h_2_fu_442 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) test_hmac_sha256_sparsemux_129_6_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 32 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 32 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 32 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 32 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 32 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 32 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 32 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 32 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 32 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 32 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 32 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 32 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 32 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 32 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 32 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 32 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 32 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 32 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 32 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 32 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 32 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 32 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 32 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 32 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 32 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 32 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 32 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 32 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 32 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 32 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 32 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 32 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sparsemux_129_6_32_1_1_U117(
    .din0(32'd1116352408),
    .din1(32'd1899447441),
    .din2(32'd3049323471),
    .din3(32'd3921009573),
    .din4(32'd961987163),
    .din5(32'd1508970993),
    .din6(32'd2453635748),
    .din7(32'd2870763221),
    .din8(32'd3624381080),
    .din9(32'd310598401),
    .din10(32'd607225278),
    .din11(32'd1426881987),
    .din12(32'd1925078388),
    .din13(32'd2162078206),
    .din14(32'd2614888103),
    .din15(32'd3248222580),
    .din16(32'd3835390401),
    .din17(32'd4022224774),
    .din18(32'd264347078),
    .din19(32'd604807628),
    .din20(32'd770255983),
    .din21(32'd1249150122),
    .din22(32'd1555081692),
    .din23(32'd1996064986),
    .din24(32'd2554220882),
    .din25(32'd2821834349),
    .din26(32'd2952996808),
    .din27(32'd3210313671),
    .din28(32'd3336571891),
    .din29(32'd3584528711),
    .din30(32'd113926993),
    .din31(32'd338241895),
    .din32(32'd666307205),
    .din33(32'd773529912),
    .din34(32'd1294757372),
    .din35(32'd1396182291),
    .din36(32'd1695183700),
    .din37(32'd1986661051),
    .din38(32'd2177026350),
    .din39(32'd2456956037),
    .din40(32'd2730485921),
    .din41(32'd2820302411),
    .din42(32'd3259730800),
    .din43(32'd3345764771),
    .din44(32'd3516065817),
    .din45(32'd3600352804),
    .din46(32'd4094571909),
    .din47(32'd275423344),
    .din48(32'd430227734),
    .din49(32'd506948616),
    .din50(32'd659060556),
    .din51(32'd883997877),
    .din52(32'd958139571),
    .din53(32'd1322822218),
    .din54(32'd1537002063),
    .din55(32'd1747873779),
    .din56(32'd1955562222),
    .din57(32'd2024104815),
    .din58(32'd2227730452),
    .din59(32'd2361852424),
    .din60(32'd2428436474),
    .din61(32'd2756734187),
    .din62(32'd3204031479),
    .din63(32'd3329325298),
    .def(Kt_1_fu_902_p129),
    .sel(trunc_ln600_reg_1483_pp0_iter1_reg),
    .dout(Kt_1_fu_902_p131)
);

test_hmac_sha256_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Kt_fu_394 <= 32'd1116352408;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            Kt_fu_394 <= Kt_1_fu_902_p131;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            b_1_fu_430 <= a;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            b_1_fu_430 <= a_2_fu_896_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_1_fu_378 <= b;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            c_1_fu_378 <= b_1_fu_430;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_1_fu_382 <= d;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            d_1_fu_382 <= d_2_fu_434;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_2_fu_434 <= c;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            d_2_fu_434 <= c_1_fu_378;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            f_1_fu_438 <= e;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            f_1_fu_438 <= e_2_fu_824_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            g_1_fu_386 <= f;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            g_1_fu_386 <= f_1_fu_438;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            h_1_fu_390 <= h;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            h_1_fu_390 <= h_2_fu_442;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            h_2_fu_442 <= g;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
            h_2_fu_442 <= g_1_fu_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln682_fu_609_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_374 <= t_2_fu_615_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_374 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Wt_reg_1488 <= w_strm_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        a_2_reg_1493 <= a_2_fu_896_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln6888_fu_426 <= add_ln688_fu_1280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd0))) begin
        add_ln6897_fu_422 <= add_ln689_fu_1165_p2;
        add_ln6906_fu_418 <= add_ln690_fu_1170_p2;
        add_ln6915_fu_414 <= add_ln691_fu_1175_p2;
        add_ln6924_fu_410 <= add_ln692_fu_1180_p2;
        add_ln6933_fu_406 <= add_ln693_fu_1185_p2;
        add_ln6942_fu_402 <= add_ln694_fu_1190_p2;
        add_ln6951_fu_398 <= add_ln695_fu_1195_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln682_reg_1479 <= icmp_ln682_fu_609_p2;
        icmp_ln682_reg_1479_pp0_iter1_reg <= icmp_ln682_reg_1479;
        trunc_ln600_reg_1483 <= trunc_ln600_fu_621_p1;
        trunc_ln600_reg_1483_pp0_iter1_reg <= trunc_ln600_reg_1483;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6888_out_ap_vld = 1'b1;
    end else begin
        add_ln6888_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6897_out_ap_vld = 1'b1;
    end else begin
        add_ln6897_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6906_out_ap_vld = 1'b1;
    end else begin
        add_ln6906_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6915_out_ap_vld = 1'b1;
    end else begin
        add_ln6915_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6924_out_ap_vld = 1'b1;
    end else begin
        add_ln6924_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6933_out_ap_vld = 1'b1;
    end else begin
        add_ln6933_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6942_out_ap_vld = 1'b1;
    end else begin
        add_ln6942_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        add_ln6951_out_ap_vld = 1'b1;
    end else begin
        add_ln6951_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln682_fu_609_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln682_reg_1479_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_t_1 = t_fu_374;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln682_reg_1479 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_strm_blk_n = w_strm_empty_n;
    end else begin
        w_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln682_reg_1479 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_strm_read = 1'b1;
    end else begin
        w_strm_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Kt_1_fu_902_p129 = 'bx;

assign T1_fu_776_p2 = (add_ln580_fu_771_p2 + add_ln580_2_fu_765_p2);

assign a_2_fu_896_p2 = (add_ln591_fu_890_p2 + xor_ln591_3_fu_884_p2);

assign add_ln580_1_fu_759_p2 = (Kt_fu_394 + h_1_fu_390);

assign add_ln580_2_fu_765_p2 = (add_ln580_1_fu_759_p2 + xor_ln580_3_fu_753_p2);

assign add_ln580_fu_771_p2 = (xor_ln580_1_fu_741_p2 + Wt_reg_1488);

assign add_ln591_fu_890_p2 = (T1_fu_776_p2 + xor_ln591_1_fu_864_p2);

assign add_ln6888_out = add_ln6888_fu_426;

assign add_ln688_fu_1280_p2 = (a_2_reg_1493 + a);

assign add_ln6897_out = add_ln6897_fu_422;

assign add_ln689_fu_1165_p2 = (b_1_fu_430 + b);

assign add_ln6906_out = add_ln6906_fu_418;

assign add_ln690_fu_1170_p2 = (c_1_fu_378 + c);

assign add_ln6915_out = add_ln6915_fu_414;

assign add_ln691_fu_1175_p2 = (d_2_fu_434 + d);

assign add_ln6924_out = add_ln6924_fu_410;

assign add_ln692_fu_1180_p2 = (e_2_fu_824_p2 + e);

assign add_ln6933_out = add_ln6933_fu_406;

assign add_ln693_fu_1185_p2 = (f_1_fu_438 + f);

assign add_ln6942_out = add_ln6942_fu_402;

assign add_ln694_fu_1190_p2 = (g_1_fu_386 + g);

assign add_ln6951_out = add_ln6951_fu_398;

assign add_ln695_fu_1195_p2 = (h_2_fu_442 + h);

assign and_ln580_1_fu_727_p2 = (xor_ln580_fu_699_p2 & h_2_fu_442);

assign and_ln580_fu_721_p2 = (g_1_fu_386 & f_1_fu_438);

assign and_ln591_1_fu_842_p2 = (d_2_fu_434 & c_1_fu_378);

assign and_ln591_fu_836_p2 = (xor_ln591_fu_830_p2 & b_1_fu_430);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((icmp_ln682_reg_1479 == 1'd0) & (w_strm_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign e_2_fu_824_p2 = (T1_fu_776_p2 + d_1_fu_382);

assign icmp_ln682_fu_609_p2 = ((ap_sig_allocacmp_t_1 == 7'd64) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_782_p4 = {{b_1_fu_430[31:2]}};

assign lshr_ln580_1_fu_671_p4 = {{f_1_fu_438[31:11]}};

assign lshr_ln580_2_fu_685_p4 = {{f_1_fu_438[31:25]}};

assign lshr_ln581_1_fu_796_p4 = {{b_1_fu_430[31:13]}};

assign lshr_ln581_2_fu_810_p4 = {{b_1_fu_430[31:22]}};

assign lshr_ln_fu_657_p4 = {{f_1_fu_438[31:6]}};

assign or_ln1_fu_848_p3 = {{trunc_ln581_fu_792_p1}, {lshr_ln1_fu_782_p4}};

assign or_ln580_1_fu_713_p3 = {{trunc_ln580_1_fu_681_p1}, {lshr_ln580_1_fu_671_p4}};

assign or_ln580_2_fu_733_p3 = {{trunc_ln580_2_fu_695_p1}, {lshr_ln580_2_fu_685_p4}};

assign or_ln591_1_fu_856_p3 = {{trunc_ln581_1_fu_806_p1}, {lshr_ln581_1_fu_796_p4}};

assign or_ln591_2_fu_870_p3 = {{trunc_ln581_2_fu_820_p1}, {lshr_ln581_2_fu_810_p4}};

assign or_ln_fu_705_p3 = {{trunc_ln580_fu_667_p1}, {lshr_ln_fu_657_p4}};

assign t_2_fu_615_p2 = (ap_sig_allocacmp_t_1 + 7'd1);

assign trunc_ln580_1_fu_681_p1 = f_1_fu_438[10:0];

assign trunc_ln580_2_fu_695_p1 = f_1_fu_438[24:0];

assign trunc_ln580_fu_667_p1 = f_1_fu_438[5:0];

assign trunc_ln581_1_fu_806_p1 = b_1_fu_430[12:0];

assign trunc_ln581_2_fu_820_p1 = b_1_fu_430[21:0];

assign trunc_ln581_fu_792_p1 = b_1_fu_430[1:0];

assign trunc_ln600_fu_621_p1 = t_2_fu_615_p2[5:0];

assign xor_ln580_1_fu_741_p2 = (and_ln580_fu_721_p2 ^ and_ln580_1_fu_727_p2);

assign xor_ln580_2_fu_747_p2 = (or_ln580_2_fu_733_p3 ^ or_ln580_1_fu_713_p3);

assign xor_ln580_3_fu_753_p2 = (xor_ln580_2_fu_747_p2 ^ or_ln_fu_705_p3);

assign xor_ln580_fu_699_p2 = (f_1_fu_438 ^ 32'd4294967295);

assign xor_ln591_1_fu_864_p2 = (and_ln591_fu_836_p2 ^ and_ln591_1_fu_842_p2);

assign xor_ln591_2_fu_878_p2 = (or_ln591_2_fu_870_p3 ^ or_ln591_1_fu_856_p3);

assign xor_ln591_3_fu_884_p2 = (xor_ln591_2_fu_878_p2 ^ or_ln1_fu_848_p3);

assign xor_ln591_fu_830_p2 = (d_2_fu_434 ^ c_1_fu_378);

endmodule //test_hmac_sha256_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS
