-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_hmac_sha256_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    w_strm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    w_strm_empty_n : IN STD_LOGIC;
    w_strm_read : OUT STD_LOGIC;
    w_strm_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    w_strm_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    h : IN STD_LOGIC_VECTOR (31 downto 0);
    g : IN STD_LOGIC_VECTOR (31 downto 0);
    f : IN STD_LOGIC_VECTOR (31 downto 0);
    e : IN STD_LOGIC_VECTOR (31 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    c : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    add_ln6888_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6888_out_ap_vld : OUT STD_LOGIC;
    add_ln6897_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6897_out_ap_vld : OUT STD_LOGIC;
    add_ln6906_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6906_out_ap_vld : OUT STD_LOGIC;
    add_ln6915_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6915_out_ap_vld : OUT STD_LOGIC;
    add_ln6924_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6924_out_ap_vld : OUT STD_LOGIC;
    add_ln6933_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6933_out_ap_vld : OUT STD_LOGIC;
    add_ln6942_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6942_out_ap_vld : OUT STD_LOGIC;
    add_ln6951_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_ln6951_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of test_hmac_sha256_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_428A2F98 : STD_LOGIC_VECTOR (31 downto 0) := "01000010100010100010111110011000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_71374491 : STD_LOGIC_VECTOR (31 downto 0) := "01110001001101110100010010010001";
    constant ap_const_lv32_B5C0FBCF : STD_LOGIC_VECTOR (31 downto 0) := "10110101110000001111101111001111";
    constant ap_const_lv32_E9B5DBA5 : STD_LOGIC_VECTOR (31 downto 0) := "11101001101101011101101110100101";
    constant ap_const_lv32_3956C25B : STD_LOGIC_VECTOR (31 downto 0) := "00111001010101101100001001011011";
    constant ap_const_lv32_59F111F1 : STD_LOGIC_VECTOR (31 downto 0) := "01011001111100010001000111110001";
    constant ap_const_lv32_923F82A4 : STD_LOGIC_VECTOR (31 downto 0) := "10010010001111111000001010100100";
    constant ap_const_lv32_AB1C5ED5 : STD_LOGIC_VECTOR (31 downto 0) := "10101011000111000101111011010101";
    constant ap_const_lv32_D807AA98 : STD_LOGIC_VECTOR (31 downto 0) := "11011000000001111010101010011000";
    constant ap_const_lv32_12835B01 : STD_LOGIC_VECTOR (31 downto 0) := "00010010100000110101101100000001";
    constant ap_const_lv32_243185BE : STD_LOGIC_VECTOR (31 downto 0) := "00100100001100011000010110111110";
    constant ap_const_lv32_550C7DC3 : STD_LOGIC_VECTOR (31 downto 0) := "01010101000011000111110111000011";
    constant ap_const_lv32_72BE5D74 : STD_LOGIC_VECTOR (31 downto 0) := "01110010101111100101110101110100";
    constant ap_const_lv32_80DEB1FE : STD_LOGIC_VECTOR (31 downto 0) := "10000000110111101011000111111110";
    constant ap_const_lv32_9BDC06A7 : STD_LOGIC_VECTOR (31 downto 0) := "10011011110111000000011010100111";
    constant ap_const_lv32_C19BF174 : STD_LOGIC_VECTOR (31 downto 0) := "11000001100110111111000101110100";
    constant ap_const_lv32_E49B69C1 : STD_LOGIC_VECTOR (31 downto 0) := "11100100100110110110100111000001";
    constant ap_const_lv32_EFBE4786 : STD_LOGIC_VECTOR (31 downto 0) := "11101111101111100100011110000110";
    constant ap_const_lv32_FC19DC6 : STD_LOGIC_VECTOR (31 downto 0) := "00001111110000011001110111000110";
    constant ap_const_lv32_240CA1CC : STD_LOGIC_VECTOR (31 downto 0) := "00100100000011001010000111001100";
    constant ap_const_lv32_2DE92C6F : STD_LOGIC_VECTOR (31 downto 0) := "00101101111010010010110001101111";
    constant ap_const_lv32_4A7484AA : STD_LOGIC_VECTOR (31 downto 0) := "01001010011101001000010010101010";
    constant ap_const_lv32_5CB0A9DC : STD_LOGIC_VECTOR (31 downto 0) := "01011100101100001010100111011100";
    constant ap_const_lv32_76F988DA : STD_LOGIC_VECTOR (31 downto 0) := "01110110111110011000100011011010";
    constant ap_const_lv32_983E5152 : STD_LOGIC_VECTOR (31 downto 0) := "10011000001111100101000101010010";
    constant ap_const_lv32_A831C66D : STD_LOGIC_VECTOR (31 downto 0) := "10101000001100011100011001101101";
    constant ap_const_lv32_B00327C8 : STD_LOGIC_VECTOR (31 downto 0) := "10110000000000110010011111001000";
    constant ap_const_lv32_BF597FC7 : STD_LOGIC_VECTOR (31 downto 0) := "10111111010110010111111111000111";
    constant ap_const_lv32_C6E00BF3 : STD_LOGIC_VECTOR (31 downto 0) := "11000110111000000000101111110011";
    constant ap_const_lv32_D5A79147 : STD_LOGIC_VECTOR (31 downto 0) := "11010101101001111001000101000111";
    constant ap_const_lv32_6CA6351 : STD_LOGIC_VECTOR (31 downto 0) := "00000110110010100110001101010001";
    constant ap_const_lv32_14292967 : STD_LOGIC_VECTOR (31 downto 0) := "00010100001010010010100101100111";
    constant ap_const_lv32_27B70A85 : STD_LOGIC_VECTOR (31 downto 0) := "00100111101101110000101010000101";
    constant ap_const_lv32_2E1B2138 : STD_LOGIC_VECTOR (31 downto 0) := "00101110000110110010000100111000";
    constant ap_const_lv32_4D2C6DFC : STD_LOGIC_VECTOR (31 downto 0) := "01001101001011000110110111111100";
    constant ap_const_lv32_53380D13 : STD_LOGIC_VECTOR (31 downto 0) := "01010011001110000000110100010011";
    constant ap_const_lv32_650A7354 : STD_LOGIC_VECTOR (31 downto 0) := "01100101000010100111001101010100";
    constant ap_const_lv32_766A0ABB : STD_LOGIC_VECTOR (31 downto 0) := "01110110011010100000101010111011";
    constant ap_const_lv32_81C2C92E : STD_LOGIC_VECTOR (31 downto 0) := "10000001110000101100100100101110";
    constant ap_const_lv32_92722C85 : STD_LOGIC_VECTOR (31 downto 0) := "10010010011100100010110010000101";
    constant ap_const_lv32_A2BFE8A1 : STD_LOGIC_VECTOR (31 downto 0) := "10100010101111111110100010100001";
    constant ap_const_lv32_A81A664B : STD_LOGIC_VECTOR (31 downto 0) := "10101000000110100110011001001011";
    constant ap_const_lv32_C24B8B70 : STD_LOGIC_VECTOR (31 downto 0) := "11000010010010111000101101110000";
    constant ap_const_lv32_C76C51A3 : STD_LOGIC_VECTOR (31 downto 0) := "11000111011011000101000110100011";
    constant ap_const_lv32_D192E819 : STD_LOGIC_VECTOR (31 downto 0) := "11010001100100101110100000011001";
    constant ap_const_lv32_D6990624 : STD_LOGIC_VECTOR (31 downto 0) := "11010110100110010000011000100100";
    constant ap_const_lv32_F40E3585 : STD_LOGIC_VECTOR (31 downto 0) := "11110100000011100011010110000101";
    constant ap_const_lv32_106AA070 : STD_LOGIC_VECTOR (31 downto 0) := "00010000011010101010000001110000";
    constant ap_const_lv32_19A4C116 : STD_LOGIC_VECTOR (31 downto 0) := "00011001101001001100000100010110";
    constant ap_const_lv32_1E376C08 : STD_LOGIC_VECTOR (31 downto 0) := "00011110001101110110110000001000";
    constant ap_const_lv32_2748774C : STD_LOGIC_VECTOR (31 downto 0) := "00100111010010000111011101001100";
    constant ap_const_lv32_34B0BCB5 : STD_LOGIC_VECTOR (31 downto 0) := "00110100101100001011110010110101";
    constant ap_const_lv32_391C0CB3 : STD_LOGIC_VECTOR (31 downto 0) := "00111001000111000000110010110011";
    constant ap_const_lv32_4ED8AA4A : STD_LOGIC_VECTOR (31 downto 0) := "01001110110110001010101001001010";
    constant ap_const_lv32_5B9CCA4F : STD_LOGIC_VECTOR (31 downto 0) := "01011011100111001100101001001111";
    constant ap_const_lv32_682E6FF3 : STD_LOGIC_VECTOR (31 downto 0) := "01101000001011100110111111110011";
    constant ap_const_lv32_748F82EE : STD_LOGIC_VECTOR (31 downto 0) := "01110100100011111000001011101110";
    constant ap_const_lv32_78A5636F : STD_LOGIC_VECTOR (31 downto 0) := "01111000101001010110001101101111";
    constant ap_const_lv32_84C87814 : STD_LOGIC_VECTOR (31 downto 0) := "10000100110010000111100000010100";
    constant ap_const_lv32_8CC70208 : STD_LOGIC_VECTOR (31 downto 0) := "10001100110001110000001000001000";
    constant ap_const_lv32_90BEFFFA : STD_LOGIC_VECTOR (31 downto 0) := "10010000101111101111111111111010";
    constant ap_const_lv32_A4506CEB : STD_LOGIC_VECTOR (31 downto 0) := "10100100010100000110110011101011";
    constant ap_const_lv32_BEF9A3F7 : STD_LOGIC_VECTOR (31 downto 0) := "10111110111110011010001111110111";
    constant ap_const_lv32_C67178F2 : STD_LOGIC_VECTOR (31 downto 0) := "11000110011100010111100011110010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln682_reg_1481 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln682_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal w_strm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln682_reg_1481_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal T1_fu_1046_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln591_3_fu_1154_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln591_3_reg_1541 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1094_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_2_fu_1226_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal t_fu_374 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal t_2_fu_615_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal c_1_fu_378 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal d_1_fu_382 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal g_1_fu_386 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal h_1_fu_390 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_h_1_load : STD_LOGIC_VECTOR (31 downto 0);
    signal Kt_fu_394 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal Kt_1_fu_637_p131 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6951_fu_398 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1191_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal add_ln6942_fu_402 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6933_fu_406 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1181_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6924_fu_410 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1236_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6915_fu_414 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1176_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6906_fu_418 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1171_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6897_fu_422 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln6888_fu_426 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1231_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_1_fu_430 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_a_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal d_2_fu_434 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal f_1_fu_438 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_e_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal h_2_fu_442 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal Kt_1_fu_637_p129 : STD_LOGIC_VECTOR (31 downto 0);
    signal Kt_1_fu_637_p130 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln580_fu_942_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_fu_932_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln580_1_fu_956_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln580_1_fu_946_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal xor_ln580_fu_974_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln580_2_fu_970_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal lshr_ln580_2_fu_960_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln580_fu_996_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln580_1_fu_1002_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln580_1_fu_988_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln580_2_fu_1008_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln580_2_fu_1022_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_fu_980_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_627_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln580_2_fu_1034_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln580_fu_1040_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln580_fu_1040_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln580_2_fu_1034_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln591_fu_1100_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln581_fu_1062_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln1_fu_1052_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln581_1_fu_1076_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln581_1_fu_1066_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal and_ln591_fu_1106_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln591_1_fu_1112_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln581_2_fu_1090_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln581_2_fu_1080_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln591_1_fu_1126_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln591_2_fu_1140_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln591_2_fu_1148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1_fu_1118_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1160_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_627_ce : STD_LOGIC;
    signal grp_fu_1094_ce : STD_LOGIC;
    signal grp_fu_1160_ce : STD_LOGIC;
    signal grp_fu_1166_ce : STD_LOGIC;
    signal grp_fu_1171_ce : STD_LOGIC;
    signal grp_fu_1176_ce : STD_LOGIC;
    signal grp_fu_1181_ce : STD_LOGIC;
    signal grp_fu_1186_ce : STD_LOGIC;
    signal grp_fu_1191_ce : STD_LOGIC;
    signal grp_fu_1231_ce : STD_LOGIC;
    signal grp_fu_1236_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal Kt_1_fu_637_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p81 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p83 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p85 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p87 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p89 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p91 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p93 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p95 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p97 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p99 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p101 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p103 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p105 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p107 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p109 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p111 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p113 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p115 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p117 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p119 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p121 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p123 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p125 : STD_LOGIC_VECTOR (5 downto 0);
    signal Kt_1_fu_637_p127 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component test_hmac_sha256_add_32ns_32ns_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component test_hmac_sha256_sparsemux_129_6_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (5 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (5 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (5 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (5 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (5 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (5 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (5 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (5 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (5 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (5 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (5 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (5 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (5 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (5 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (5 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (5 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (5 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (5 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (5 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (5 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (5 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (5 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (5 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (5 downto 0);
        din63_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        din32 : IN STD_LOGIC_VECTOR (31 downto 0);
        din33 : IN STD_LOGIC_VECTOR (31 downto 0);
        din34 : IN STD_LOGIC_VECTOR (31 downto 0);
        din35 : IN STD_LOGIC_VECTOR (31 downto 0);
        din36 : IN STD_LOGIC_VECTOR (31 downto 0);
        din37 : IN STD_LOGIC_VECTOR (31 downto 0);
        din38 : IN STD_LOGIC_VECTOR (31 downto 0);
        din39 : IN STD_LOGIC_VECTOR (31 downto 0);
        din40 : IN STD_LOGIC_VECTOR (31 downto 0);
        din41 : IN STD_LOGIC_VECTOR (31 downto 0);
        din42 : IN STD_LOGIC_VECTOR (31 downto 0);
        din43 : IN STD_LOGIC_VECTOR (31 downto 0);
        din44 : IN STD_LOGIC_VECTOR (31 downto 0);
        din45 : IN STD_LOGIC_VECTOR (31 downto 0);
        din46 : IN STD_LOGIC_VECTOR (31 downto 0);
        din47 : IN STD_LOGIC_VECTOR (31 downto 0);
        din48 : IN STD_LOGIC_VECTOR (31 downto 0);
        din49 : IN STD_LOGIC_VECTOR (31 downto 0);
        din50 : IN STD_LOGIC_VECTOR (31 downto 0);
        din51 : IN STD_LOGIC_VECTOR (31 downto 0);
        din52 : IN STD_LOGIC_VECTOR (31 downto 0);
        din53 : IN STD_LOGIC_VECTOR (31 downto 0);
        din54 : IN STD_LOGIC_VECTOR (31 downto 0);
        din55 : IN STD_LOGIC_VECTOR (31 downto 0);
        din56 : IN STD_LOGIC_VECTOR (31 downto 0);
        din57 : IN STD_LOGIC_VECTOR (31 downto 0);
        din58 : IN STD_LOGIC_VECTOR (31 downto 0);
        din59 : IN STD_LOGIC_VECTOR (31 downto 0);
        din60 : IN STD_LOGIC_VECTOR (31 downto 0);
        din61 : IN STD_LOGIC_VECTOR (31 downto 0);
        din62 : IN STD_LOGIC_VECTOR (31 downto 0);
        din63 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component test_hmac_sha256_add_32ns_32ns_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component test_hmac_sha256_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    add_32ns_32ns_32_2_1_U139 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Kt_fu_394,
        din1 => ap_sig_allocacmp_h_1_load,
        ce => grp_fu_627_ce,
        dout => grp_fu_627_p2);

    sparsemux_129_6_32_1_1_U140 : component test_hmac_sha256_sparsemux_129_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "000001",
        din1_WIDTH => 32,
        CASE2 => "000010",
        din2_WIDTH => 32,
        CASE3 => "000011",
        din3_WIDTH => 32,
        CASE4 => "000100",
        din4_WIDTH => 32,
        CASE5 => "000101",
        din5_WIDTH => 32,
        CASE6 => "000110",
        din6_WIDTH => 32,
        CASE7 => "000111",
        din7_WIDTH => 32,
        CASE8 => "001000",
        din8_WIDTH => 32,
        CASE9 => "001001",
        din9_WIDTH => 32,
        CASE10 => "001010",
        din10_WIDTH => 32,
        CASE11 => "001011",
        din11_WIDTH => 32,
        CASE12 => "001100",
        din12_WIDTH => 32,
        CASE13 => "001101",
        din13_WIDTH => 32,
        CASE14 => "001110",
        din14_WIDTH => 32,
        CASE15 => "001111",
        din15_WIDTH => 32,
        CASE16 => "010000",
        din16_WIDTH => 32,
        CASE17 => "010001",
        din17_WIDTH => 32,
        CASE18 => "010010",
        din18_WIDTH => 32,
        CASE19 => "010011",
        din19_WIDTH => 32,
        CASE20 => "010100",
        din20_WIDTH => 32,
        CASE21 => "010101",
        din21_WIDTH => 32,
        CASE22 => "010110",
        din22_WIDTH => 32,
        CASE23 => "010111",
        din23_WIDTH => 32,
        CASE24 => "011000",
        din24_WIDTH => 32,
        CASE25 => "011001",
        din25_WIDTH => 32,
        CASE26 => "011010",
        din26_WIDTH => 32,
        CASE27 => "011011",
        din27_WIDTH => 32,
        CASE28 => "011100",
        din28_WIDTH => 32,
        CASE29 => "011101",
        din29_WIDTH => 32,
        CASE30 => "011110",
        din30_WIDTH => 32,
        CASE31 => "011111",
        din31_WIDTH => 32,
        CASE32 => "100000",
        din32_WIDTH => 32,
        CASE33 => "100001",
        din33_WIDTH => 32,
        CASE34 => "100010",
        din34_WIDTH => 32,
        CASE35 => "100011",
        din35_WIDTH => 32,
        CASE36 => "100100",
        din36_WIDTH => 32,
        CASE37 => "100101",
        din37_WIDTH => 32,
        CASE38 => "100110",
        din38_WIDTH => 32,
        CASE39 => "100111",
        din39_WIDTH => 32,
        CASE40 => "101000",
        din40_WIDTH => 32,
        CASE41 => "101001",
        din41_WIDTH => 32,
        CASE42 => "101010",
        din42_WIDTH => 32,
        CASE43 => "101011",
        din43_WIDTH => 32,
        CASE44 => "101100",
        din44_WIDTH => 32,
        CASE45 => "101101",
        din45_WIDTH => 32,
        CASE46 => "101110",
        din46_WIDTH => 32,
        CASE47 => "101111",
        din47_WIDTH => 32,
        CASE48 => "110000",
        din48_WIDTH => 32,
        CASE49 => "110001",
        din49_WIDTH => 32,
        CASE50 => "110010",
        din50_WIDTH => 32,
        CASE51 => "110011",
        din51_WIDTH => 32,
        CASE52 => "110100",
        din52_WIDTH => 32,
        CASE53 => "110101",
        din53_WIDTH => 32,
        CASE54 => "110110",
        din54_WIDTH => 32,
        CASE55 => "110111",
        din55_WIDTH => 32,
        CASE56 => "111000",
        din56_WIDTH => 32,
        CASE57 => "111001",
        din57_WIDTH => 32,
        CASE58 => "111010",
        din58_WIDTH => 32,
        CASE59 => "111011",
        din59_WIDTH => 32,
        CASE60 => "111100",
        din60_WIDTH => 32,
        CASE61 => "111101",
        din61_WIDTH => 32,
        CASE62 => "111110",
        din62_WIDTH => 32,
        CASE63 => "111111",
        din63_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_428A2F98,
        din1 => ap_const_lv32_71374491,
        din2 => ap_const_lv32_B5C0FBCF,
        din3 => ap_const_lv32_E9B5DBA5,
        din4 => ap_const_lv32_3956C25B,
        din5 => ap_const_lv32_59F111F1,
        din6 => ap_const_lv32_923F82A4,
        din7 => ap_const_lv32_AB1C5ED5,
        din8 => ap_const_lv32_D807AA98,
        din9 => ap_const_lv32_12835B01,
        din10 => ap_const_lv32_243185BE,
        din11 => ap_const_lv32_550C7DC3,
        din12 => ap_const_lv32_72BE5D74,
        din13 => ap_const_lv32_80DEB1FE,
        din14 => ap_const_lv32_9BDC06A7,
        din15 => ap_const_lv32_C19BF174,
        din16 => ap_const_lv32_E49B69C1,
        din17 => ap_const_lv32_EFBE4786,
        din18 => ap_const_lv32_FC19DC6,
        din19 => ap_const_lv32_240CA1CC,
        din20 => ap_const_lv32_2DE92C6F,
        din21 => ap_const_lv32_4A7484AA,
        din22 => ap_const_lv32_5CB0A9DC,
        din23 => ap_const_lv32_76F988DA,
        din24 => ap_const_lv32_983E5152,
        din25 => ap_const_lv32_A831C66D,
        din26 => ap_const_lv32_B00327C8,
        din27 => ap_const_lv32_BF597FC7,
        din28 => ap_const_lv32_C6E00BF3,
        din29 => ap_const_lv32_D5A79147,
        din30 => ap_const_lv32_6CA6351,
        din31 => ap_const_lv32_14292967,
        din32 => ap_const_lv32_27B70A85,
        din33 => ap_const_lv32_2E1B2138,
        din34 => ap_const_lv32_4D2C6DFC,
        din35 => ap_const_lv32_53380D13,
        din36 => ap_const_lv32_650A7354,
        din37 => ap_const_lv32_766A0ABB,
        din38 => ap_const_lv32_81C2C92E,
        din39 => ap_const_lv32_92722C85,
        din40 => ap_const_lv32_A2BFE8A1,
        din41 => ap_const_lv32_A81A664B,
        din42 => ap_const_lv32_C24B8B70,
        din43 => ap_const_lv32_C76C51A3,
        din44 => ap_const_lv32_D192E819,
        din45 => ap_const_lv32_D6990624,
        din46 => ap_const_lv32_F40E3585,
        din47 => ap_const_lv32_106AA070,
        din48 => ap_const_lv32_19A4C116,
        din49 => ap_const_lv32_1E376C08,
        din50 => ap_const_lv32_2748774C,
        din51 => ap_const_lv32_34B0BCB5,
        din52 => ap_const_lv32_391C0CB3,
        din53 => ap_const_lv32_4ED8AA4A,
        din54 => ap_const_lv32_5B9CCA4F,
        din55 => ap_const_lv32_682E6FF3,
        din56 => ap_const_lv32_748F82EE,
        din57 => ap_const_lv32_78A5636F,
        din58 => ap_const_lv32_84C87814,
        din59 => ap_const_lv32_8CC70208,
        din60 => ap_const_lv32_90BEFFFA,
        din61 => ap_const_lv32_A4506CEB,
        din62 => ap_const_lv32_BEF9A3F7,
        din63 => ap_const_lv32_C67178F2,
        def => Kt_1_fu_637_p129,
        sel => Kt_1_fu_637_p130,
        dout => Kt_1_fu_637_p131);

    add_32ns_32ns_32_1_1_U141 : component test_hmac_sha256_add_32ns_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_627_p2,
        din1 => add_ln580_2_fu_1034_p1,
        dout => add_ln580_2_fu_1034_p2);

    add_32ns_32ns_32_1_1_U142 : component test_hmac_sha256_add_32ns_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => add_ln580_fu_1040_p0,
        din1 => w_strm_dout,
        dout => add_ln580_fu_1040_p2);

    add_32ns_32ns_32_1_1_U143 : component test_hmac_sha256_add_32ns_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => add_ln580_fu_1040_p2,
        din1 => add_ln580_2_fu_1034_p2,
        dout => T1_fu_1046_p2);

    add_32ns_32ns_32_2_1_U144 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => T1_fu_1046_p2,
        din1 => d_1_fu_382,
        ce => grp_fu_1094_ce,
        dout => grp_fu_1094_p2);

    add_32ns_32ns_32_2_1_U145 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => T1_fu_1046_p2,
        din1 => grp_fu_1160_p1,
        ce => grp_fu_1160_ce,
        dout => grp_fu_1160_p2);

    add_32ns_32ns_32_2_1_U146 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_sig_allocacmp_a_3,
        din1 => b,
        ce => grp_fu_1166_ce,
        dout => grp_fu_1166_p2);

    add_32ns_32ns_32_2_1_U147 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => c_1_fu_378,
        din1 => c,
        ce => grp_fu_1171_ce,
        dout => grp_fu_1171_p2);

    add_32ns_32ns_32_2_1_U148 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => d_2_fu_434,
        din1 => d,
        ce => grp_fu_1176_ce,
        dout => grp_fu_1176_p2);

    add_32ns_32ns_32_2_1_U149 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_sig_allocacmp_e_3,
        din1 => f,
        ce => grp_fu_1181_ce,
        dout => grp_fu_1181_p2);

    add_32ns_32ns_32_2_1_U150 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => g_1_fu_386,
        din1 => g,
        ce => grp_fu_1186_ce,
        dout => grp_fu_1186_p2);

    add_32ns_32ns_32_2_1_U151 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => h_2_fu_442,
        din1 => h,
        ce => grp_fu_1191_ce,
        dout => grp_fu_1191_p2);

    add_32ns_32ns_32_1_1_U152 : component test_hmac_sha256_add_32ns_32ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_1160_p2,
        din1 => xor_ln591_3_reg_1541,
        dout => a_2_fu_1226_p2);

    add_32ns_32ns_32_2_1_U153 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_2_fu_1226_p2,
        din1 => a,
        ce => grp_fu_1231_ce,
        dout => grp_fu_1231_p2);

    add_32ns_32ns_32_2_1_U154 : component test_hmac_sha256_add_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1094_p2,
        din1 => e,
        ce => grp_fu_1236_ce,
        dout => grp_fu_1236_p2);

    flow_control_loop_pipe_sequential_init_U : component test_hmac_sha256_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    Kt_fu_394_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    Kt_fu_394 <= ap_const_lv32_428A2F98;
                elsif (((icmp_ln682_fu_609_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    Kt_fu_394 <= Kt_1_fu_637_p131;
                end if;
            end if; 
        end if;
    end process;

    b_1_fu_430_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    b_1_fu_430 <= a;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    b_1_fu_430 <= a_2_fu_1226_p2;
                end if;
            end if; 
        end if;
    end process;

    c_1_fu_378_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    c_1_fu_378 <= b;
                elsif (((icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    c_1_fu_378 <= ap_sig_allocacmp_a_3;
                end if;
            end if; 
        end if;
    end process;

    d_1_fu_382_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_1_fu_382 <= d;
                elsif (((icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    d_1_fu_382 <= d_2_fu_434;
                end if;
            end if; 
        end if;
    end process;

    d_2_fu_434_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_2_fu_434 <= c;
                elsif (((icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    d_2_fu_434 <= c_1_fu_378;
                end if;
            end if; 
        end if;
    end process;

    f_1_fu_438_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    f_1_fu_438 <= e;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    f_1_fu_438 <= grp_fu_1094_p2;
                end if;
            end if; 
        end if;
    end process;

    g_1_fu_386_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    g_1_fu_386 <= f;
                elsif (((icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    g_1_fu_386 <= ap_sig_allocacmp_e_3;
                end if;
            end if; 
        end if;
    end process;

    h_1_fu_390_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    h_1_fu_390 <= h;
                elsif (((icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    h_1_fu_390 <= h_2_fu_442;
                end if;
            end if; 
        end if;
    end process;

    h_2_fu_442_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    h_2_fu_442 <= g;
                elsif (((icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    h_2_fu_442 <= g_1_fu_386;
                end if;
            end if; 
        end if;
    end process;

    t_fu_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_374 <= ap_const_lv7_0;
                elsif (((icmp_ln682_fu_609_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    t_fu_374 <= t_2_fu_615_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                add_ln6888_fu_426 <= grp_fu_1231_p2;
                add_ln6924_fu_410 <= grp_fu_1236_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                add_ln6897_fu_422 <= grp_fu_1166_p2;
                add_ln6906_fu_418 <= grp_fu_1171_p2;
                add_ln6915_fu_414 <= grp_fu_1176_p2;
                add_ln6933_fu_406 <= grp_fu_1181_p2;
                add_ln6942_fu_402 <= grp_fu_1186_p2;
                add_ln6951_fu_398 <= grp_fu_1191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln682_reg_1481 <= icmp_ln682_fu_609_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln682_reg_1481_pp0_iter2_reg <= icmp_ln682_reg_1481;
                xor_ln591_3_reg_1541 <= xor_ln591_3_fu_1154_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Kt_1_fu_637_p129 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    Kt_1_fu_637_p130 <= t_2_fu_615_p2(6 - 1 downto 0);
    add_ln580_2_fu_1034_p1 <= (xor_ln580_2_fu_1022_p2 xor or_ln_fu_980_p3);
    add_ln580_fu_1040_p0 <= (and_ln580_fu_996_p2 xor and_ln580_1_fu_1002_p2);
    add_ln6888_out <= add_ln6888_fu_426;

    add_ln6888_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6888_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6888_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6897_out <= add_ln6897_fu_422;

    add_ln6897_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6897_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6897_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6906_out <= add_ln6906_fu_418;

    add_ln6906_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6906_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6906_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6915_out <= add_ln6915_fu_414;

    add_ln6915_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6915_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6915_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6924_out <= add_ln6924_fu_410;

    add_ln6924_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6924_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6924_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6933_out <= add_ln6933_fu_406;

    add_ln6933_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6933_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6933_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6942_out <= add_ln6942_fu_402;

    add_ln6942_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6942_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6942_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln6951_out <= add_ln6951_fu_398;

    add_ln6951_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln682_reg_1481_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln682_reg_1481_pp0_iter2_reg = ap_const_lv1_1))) then 
            add_ln6951_out_ap_vld <= ap_const_logic_1;
        else 
            add_ln6951_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    and_ln580_1_fu_1002_p2 <= (xor_ln580_fu_974_p2 and h_2_fu_442);
    and_ln580_fu_996_p2 <= (g_1_fu_386 and ap_sig_allocacmp_e_3);
    and_ln591_1_fu_1112_p2 <= (d_2_fu_434 and c_1_fu_378);
    and_ln591_fu_1106_p2 <= (xor_ln591_fu_1100_p2 and ap_sig_allocacmp_a_3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(w_strm_empty_n, icmp_ln682_reg_1481)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln682_reg_1481 = ap_const_lv1_0) and (w_strm_empty_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln682_fu_609_p2)
    begin
        if (((icmp_ln682_fu_609_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln682_reg_1481, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln682_reg_1481 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_a_3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, a_2_fu_1226_p2, b_1_fu_430)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_a_3 <= a_2_fu_1226_p2;
        else 
            ap_sig_allocacmp_a_3 <= b_1_fu_430;
        end if; 
    end process;


    ap_sig_allocacmp_e_3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, grp_fu_1094_p2, f_1_fu_438)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_e_3 <= grp_fu_1094_p2;
        else 
            ap_sig_allocacmp_e_3 <= f_1_fu_438;
        end if; 
    end process;


    ap_sig_allocacmp_h_1_load_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln682_reg_1481, ap_block_pp0_stage0, h_1_fu_390, h_2_fu_442)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_h_1_load <= h_2_fu_442;
        else 
            ap_sig_allocacmp_h_1_load <= h_1_fu_390;
        end if; 
    end process;


    grp_fu_1094_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1094_ce <= ap_const_logic_1;
        else 
            grp_fu_1094_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1160_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1160_ce <= ap_const_logic_1;
        else 
            grp_fu_1160_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1160_p1 <= (and_ln591_fu_1106_p2 xor and_ln591_1_fu_1112_p2);

    grp_fu_1166_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1166_ce <= ap_const_logic_1;
        else 
            grp_fu_1166_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1171_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1171_ce <= ap_const_logic_1;
        else 
            grp_fu_1171_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1176_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1176_ce <= ap_const_logic_1;
        else 
            grp_fu_1176_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1181_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1181_ce <= ap_const_logic_1;
        else 
            grp_fu_1181_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1186_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1186_ce <= ap_const_logic_1;
        else 
            grp_fu_1186_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1191_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1191_ce <= ap_const_logic_1;
        else 
            grp_fu_1191_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1231_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1231_ce <= ap_const_logic_1;
        else 
            grp_fu_1231_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_1236_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_1236_ce <= ap_const_logic_1;
        else 
            grp_fu_1236_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_627_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_627_ce <= ap_const_logic_1;
        else 
            grp_fu_627_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln682_fu_609_p2 <= "1" when (t_fu_374 = ap_const_lv7_40) else "0";
    lshr_ln1_fu_1052_p4 <= ap_sig_allocacmp_a_3(31 downto 2);
    lshr_ln580_1_fu_946_p4 <= ap_sig_allocacmp_e_3(31 downto 11);
    lshr_ln580_2_fu_960_p4 <= ap_sig_allocacmp_e_3(31 downto 25);
    lshr_ln581_1_fu_1066_p4 <= ap_sig_allocacmp_a_3(31 downto 13);
    lshr_ln581_2_fu_1080_p4 <= ap_sig_allocacmp_a_3(31 downto 22);
    lshr_ln_fu_932_p4 <= ap_sig_allocacmp_e_3(31 downto 6);
    or_ln1_fu_1118_p3 <= (trunc_ln581_fu_1062_p1 & lshr_ln1_fu_1052_p4);
    or_ln580_1_fu_988_p3 <= (trunc_ln580_1_fu_956_p1 & lshr_ln580_1_fu_946_p4);
    or_ln580_2_fu_1008_p3 <= (trunc_ln580_2_fu_970_p1 & lshr_ln580_2_fu_960_p4);
    or_ln591_1_fu_1126_p3 <= (trunc_ln581_1_fu_1076_p1 & lshr_ln581_1_fu_1066_p4);
    or_ln591_2_fu_1140_p3 <= (trunc_ln581_2_fu_1090_p1 & lshr_ln581_2_fu_1080_p4);
    or_ln_fu_980_p3 <= (trunc_ln580_fu_942_p1 & lshr_ln_fu_932_p4);
    t_2_fu_615_p2 <= std_logic_vector(unsigned(t_fu_374) + unsigned(ap_const_lv7_1));
    trunc_ln580_1_fu_956_p1 <= ap_sig_allocacmp_e_3(11 - 1 downto 0);
    trunc_ln580_2_fu_970_p1 <= ap_sig_allocacmp_e_3(25 - 1 downto 0);
    trunc_ln580_fu_942_p1 <= ap_sig_allocacmp_e_3(6 - 1 downto 0);
    trunc_ln581_1_fu_1076_p1 <= ap_sig_allocacmp_a_3(13 - 1 downto 0);
    trunc_ln581_2_fu_1090_p1 <= ap_sig_allocacmp_a_3(22 - 1 downto 0);
    trunc_ln581_fu_1062_p1 <= ap_sig_allocacmp_a_3(2 - 1 downto 0);

    w_strm_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, w_strm_empty_n, icmp_ln682_reg_1481, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_strm_blk_n <= w_strm_empty_n;
        else 
            w_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    w_strm_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln682_reg_1481, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln682_reg_1481 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_strm_read <= ap_const_logic_1;
        else 
            w_strm_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln580_2_fu_1022_p2 <= (or_ln580_2_fu_1008_p3 xor or_ln580_1_fu_988_p3);
    xor_ln580_fu_974_p2 <= (ap_sig_allocacmp_e_3 xor ap_const_lv32_FFFFFFFF);
    xor_ln591_2_fu_1148_p2 <= (or_ln591_2_fu_1140_p3 xor or_ln591_1_fu_1126_p3);
    xor_ln591_3_fu_1154_p2 <= (xor_ln591_2_fu_1148_p2 xor or_ln1_fu_1118_p3);
    xor_ln591_fu_1100_p2 <= (d_2_fu_434 xor c_1_fu_378);
end behav;
