-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_hmac_sha256_mergeKipad_32_64_256_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    kipadStrm_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    kipadStrm_empty_n : IN STD_LOGIC;
    kipadStrm_read : OUT STD_LOGIC;
    kipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    kipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    kopadStrm_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    kopadStrm_empty_n : IN STD_LOGIC;
    kopadStrm_read : OUT STD_LOGIC;
    kopadStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    kopadStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    msgStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    msgStrm_empty_n : IN STD_LOGIC;
    msgStrm_read : OUT STD_LOGIC;
    lenStrm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    lenStrm_empty_n : IN STD_LOGIC;
    lenStrm_read : OUT STD_LOGIC;
    eKipadStrm_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    eKipadStrm_empty_n : IN STD_LOGIC;
    eKipadStrm_read : OUT STD_LOGIC;
    eKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    eKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    mergeKipadStrm_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mergeKipadStrm_full_n : IN STD_LOGIC;
    mergeKipadStrm_write : OUT STD_LOGIC;
    mergeKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    mergeKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    mergeKipadLenStrm_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    mergeKipadLenStrm_full_n : IN STD_LOGIC;
    mergeKipadLenStrm_write : OUT STD_LOGIC;
    mergeKipadLenStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    mergeKipadLenStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    eMergeKipadLenStrm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    eMergeKipadLenStrm_full_n : IN STD_LOGIC;
    eMergeKipadLenStrm_write : OUT STD_LOGIC;
    eMergeKipadLenStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    eMergeKipadLenStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    kopad2Strm_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    kopad2Strm_full_n : IN STD_LOGIC;
    kopad2Strm_write : OUT STD_LOGIC;
    kopad2Strm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    kopad2Strm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of test_hmac_sha256_mergeKipad_32_64_256_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_40 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000001000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv68_1F : STD_LOGIC_VECTOR (67 downto 0) := "00000000000000000000000000000000000000000000000000000000000000011111";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal kipadStrm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal kopadStrm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal lenStrm_blk_n : STD_LOGIC;
    signal eKipadStrm_blk_n : STD_LOGIC;
    signal mergeKipadLenStrm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal eMergeKipadLenStrm_blk_n : STD_LOGIC;
    signal kopad2Strm_blk_n : STD_LOGIC;
    signal ml_reg_237 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal kipad_reg_243 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_142_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mergeKipadLen_reg_253 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_1_reg_258 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_done : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_idle : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_ready : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_write : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_done : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_idle : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_ready : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_msgStrm_read : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_write : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state9 : BOOLEAN;
    signal tmp_fu_147_p3 : STD_LOGIC_VECTOR (66 downto 0);
    signal grp_fu_158_p0 : STD_LOGIC_VECTOR (67 downto 0);
    signal grp_fu_158_p2 : STD_LOGIC_VECTOR (67 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component test_hmac_sha256_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mergeKipadStrm_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        mergeKipadStrm_full_n : IN STD_LOGIC;
        mergeKipadStrm_write : OUT STD_LOGIC;
        mergeKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        mergeKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        kipad : IN STD_LOGIC_VECTOR (511 downto 0) );
    end component;


    component test_hmac_sha256_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (62 downto 0);
        msgStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        msgStrm_empty_n : IN STD_LOGIC;
        msgStrm_read : OUT STD_LOGIC;
        mergeKipadStrm_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        mergeKipadStrm_full_n : IN STD_LOGIC;
        mergeKipadStrm_write : OUT STD_LOGIC;
        mergeKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        mergeKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component test_hmac_sha256_add_64ns_64ns_64_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component test_hmac_sha256_add_68ns_68ns_68_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (67 downto 0);
        din1 : IN STD_LOGIC_VECTOR (67 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (67 downto 0) );
    end component;



begin
    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126 : component test_hmac_sha256_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start,
        ap_done => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_done,
        ap_idle => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_idle,
        ap_ready => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_ready,
        mergeKipadStrm_din => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_din,
        mergeKipadStrm_full_n => mergeKipadStrm_full_n,
        mergeKipadStrm_write => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_write,
        mergeKipadStrm_num_data_valid => mergeKipadStrm_num_data_valid,
        mergeKipadStrm_fifo_cap => mergeKipadStrm_fifo_cap,
        kipad => kipad_reg_243);

    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133 : component test_hmac_sha256_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start,
        ap_done => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_done,
        ap_idle => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_idle,
        ap_ready => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_ready,
        empty => tmp_1_reg_258,
        msgStrm_dout => msgStrm_dout,
        msgStrm_empty_n => msgStrm_empty_n,
        msgStrm_read => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_msgStrm_read,
        mergeKipadStrm_din => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_din,
        mergeKipadStrm_full_n => mergeKipadStrm_full_n,
        mergeKipadStrm_write => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_write,
        mergeKipadStrm_num_data_valid => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid,
        mergeKipadStrm_fifo_cap => grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap);

    add_64ns_64ns_64_3_1_U17 : component test_hmac_sha256_add_64ns_64ns_64_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ml_reg_237,
        din1 => ap_const_lv64_40,
        ce => ap_const_logic_1,
        dout => grp_fu_142_p2);

    add_68ns_68ns_68_3_1_U18 : component test_hmac_sha256_add_68ns_68ns_68_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 68,
        din1_WIDTH => 68,
        dout_WIDTH => 68)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_158_p0,
        din1 => ap_const_lv68_1F,
        ce => ap_const_logic_1,
        dout => grp_fu_158_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_ready = ap_const_logic_1)) then 
                    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_ready = ap_const_logic_1)) then 
                    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                kipad_reg_243 <= kipadStrm_dout;
                ml_reg_237 <= lenStrm_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                mergeKipadLen_reg_253 <= grp_fu_142_p2;
                tmp_1_reg_258 <= grp_fu_158_p2(67 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, eKipadStrm_dout, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state6, ap_block_state2, grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_done, grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_done, ap_CS_fsm_state8, ap_CS_fsm_state11, ap_block_state6, ap_block_state9, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_done)
    begin
        if ((grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6)
    begin
        if ((ap_const_boolean_1 = ap_block_state6)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_done)
    begin
        if ((grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9)
    begin
        if ((ap_const_boolean_1 = ap_block_state9)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(kipadStrm_empty_n, lenStrm_empty_n, eKipadStrm_dout, eKipadStrm_empty_n, eMergeKipadLenStrm_full_n)
    begin
                ap_block_state2 <= ((eKipadStrm_empty_n = ap_const_logic_0) or ((eMergeKipadLenStrm_full_n = ap_const_logic_0) and (eKipadStrm_dout = ap_const_lv1_1)) or ((kipadStrm_empty_n = ap_const_logic_0) and (eKipadStrm_dout = ap_const_lv1_0)) or ((lenStrm_empty_n = ap_const_logic_0) and (eKipadStrm_dout = ap_const_lv1_0)));
    end process;


    ap_block_state6_assign_proc : process(mergeKipadLenStrm_full_n, eMergeKipadLenStrm_full_n)
    begin
                ap_block_state6 <= ((eMergeKipadLenStrm_full_n = ap_const_logic_0) or (mergeKipadLenStrm_full_n = ap_const_logic_0));
    end process;


    ap_block_state9_assign_proc : process(kopadStrm_empty_n, kopad2Strm_full_n)
    begin
                ap_block_state9 <= ((kopad2Strm_full_n = ap_const_logic_0) or (kopadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, eKipadStrm_dout, ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    eKipadStrm_blk_n_assign_proc : process(eKipadStrm_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            eKipadStrm_blk_n <= eKipadStrm_empty_n;
        else 
            eKipadStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    eKipadStrm_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            eKipadStrm_read <= ap_const_logic_1;
        else 
            eKipadStrm_read <= ap_const_logic_0;
        end if; 
    end process;


    eMergeKipadLenStrm_blk_n_assign_proc : process(eKipadStrm_dout, eMergeKipadLenStrm_full_n, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (eKipadStrm_dout = ap_const_lv1_1)))) then 
            eMergeKipadLenStrm_blk_n <= eMergeKipadLenStrm_full_n;
        else 
            eMergeKipadLenStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    eMergeKipadLenStrm_din_assign_proc : process(eKipadStrm_dout, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_block_state2, ap_block_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6))) then 
            eMergeKipadLenStrm_din <= ap_const_lv1_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_1))) then 
            eMergeKipadLenStrm_din <= ap_const_lv1_1;
        else 
            eMergeKipadLenStrm_din <= "X";
        end if; 
    end process;


    eMergeKipadLenStrm_write_assign_proc : process(eKipadStrm_dout, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_block_state2, ap_block_state6)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_1)))) then 
            eMergeKipadLenStrm_write <= ap_const_logic_1;
        else 
            eMergeKipadLenStrm_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_158_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_147_p3),68));
    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_ap_start_reg;
    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_ap_start_reg;
    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0(8 - 1 downto 0);
    
    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0_proc : process(mergeKipadStrm_fifo_cap)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_7(5 - 1 downto 0);
        v0_cpy := mergeKipadStrm_fifo_cap;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_7(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0_i in 0 to 32-1 loop
                v0_cpy(grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0_i) := mergeKipadStrm_fifo_cap(32-1-grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_fifo_cap0 <= resvalue(32-1 downto 0);
    end process;

    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0(8 - 1 downto 0);
    
    grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0_proc : process(mergeKipadStrm_num_data_valid)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_7(5 - 1 downto 0);
        v0_cpy := mergeKipadStrm_num_data_valid;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_7(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0_i in 0 to 32-1 loop
                v0_cpy(grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0_i) := mergeKipadStrm_num_data_valid(32-1-grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_num_data_valid0 <= resvalue(32-1 downto 0);
    end process;


    internal_ap_ready_assign_proc : process(eKipadStrm_dout, ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    kipadStrm_blk_n_assign_proc : process(kipadStrm_empty_n, eKipadStrm_dout, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (eKipadStrm_dout = ap_const_lv1_0))) then 
            kipadStrm_blk_n <= kipadStrm_empty_n;
        else 
            kipadStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    kipadStrm_read_assign_proc : process(eKipadStrm_dout, ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_0))) then 
            kipadStrm_read <= ap_const_logic_1;
        else 
            kipadStrm_read <= ap_const_logic_0;
        end if; 
    end process;


    kopad2Strm_blk_n_assign_proc : process(kopad2Strm_full_n, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            kopad2Strm_blk_n <= kopad2Strm_full_n;
        else 
            kopad2Strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    kopad2Strm_din <= kopadStrm_dout;

    kopad2Strm_write_assign_proc : process(ap_CS_fsm_state9, ap_block_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9))) then 
            kopad2Strm_write <= ap_const_logic_1;
        else 
            kopad2Strm_write <= ap_const_logic_0;
        end if; 
    end process;


    kopadStrm_blk_n_assign_proc : process(kopadStrm_empty_n, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            kopadStrm_blk_n <= kopadStrm_empty_n;
        else 
            kopadStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    kopadStrm_read_assign_proc : process(ap_CS_fsm_state9, ap_block_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9))) then 
            kopadStrm_read <= ap_const_logic_1;
        else 
            kopadStrm_read <= ap_const_logic_0;
        end if; 
    end process;


    lenStrm_blk_n_assign_proc : process(lenStrm_empty_n, eKipadStrm_dout, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (eKipadStrm_dout = ap_const_lv1_0))) then 
            lenStrm_blk_n <= lenStrm_empty_n;
        else 
            lenStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lenStrm_read_assign_proc : process(eKipadStrm_dout, ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2) and (eKipadStrm_dout = ap_const_lv1_0))) then 
            lenStrm_read <= ap_const_logic_1;
        else 
            lenStrm_read <= ap_const_logic_0;
        end if; 
    end process;


    mergeKipadLenStrm_blk_n_assign_proc : process(mergeKipadLenStrm_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            mergeKipadLenStrm_blk_n <= mergeKipadLenStrm_full_n;
        else 
            mergeKipadLenStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mergeKipadLenStrm_din <= mergeKipadLen_reg_253;

    mergeKipadLenStrm_write_assign_proc : process(ap_CS_fsm_state6, ap_block_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6))) then 
            mergeKipadLenStrm_write <= ap_const_logic_1;
        else 
            mergeKipadLenStrm_write <= ap_const_logic_0;
        end if; 
    end process;


    mergeKipadStrm_din_assign_proc : process(grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_din, grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_din, ap_CS_fsm_state8, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            mergeKipadStrm_din <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            mergeKipadStrm_din <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_din;
        else 
            mergeKipadStrm_din <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_din;
        end if; 
    end process;


    mergeKipadStrm_write_assign_proc : process(grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_write, grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_write, ap_CS_fsm_state8, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            mergeKipadStrm_write <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_mergeKipadStrm_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            mergeKipadStrm_write <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_162_2_fu_126_mergeKipadStrm_write;
        else 
            mergeKipadStrm_write <= ap_const_logic_0;
        end if; 
    end process;

    msgStrm_read <= grp_mergeKipad_32_64_256_64_Pipeline_VITIS_LOOP_171_3_fu_133_msgStrm_read;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_147_p3 <= (ml_reg_237 & ap_const_lv3_0);
end behav;
