// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_generateMsgSchedule_Pipeline_LOOP_SHA256_PREPARE_WT64 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_strm_din,
        w_strm_full_n,
        w_strm_write,
        w_strm_num_data_valid,
        w_strm_fifo_cap,
        W_reload,
        W_2_reload,
        W_3_reload,
        W_4_reload,
        W_5_reload,
        W_7_reload,
        W_8_reload,
        W_9_reload,
        W_10_reload,
        W_11_reload,
        W_12_reload,
        W_13_reload,
        W_15_reload,
        W_14_reload,
        W_6_reload,
        W_1_reload
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] w_strm_din;
input   w_strm_full_n;
output   w_strm_write;
input  [31:0] w_strm_num_data_valid;
input  [31:0] w_strm_fifo_cap;
input  [31:0] W_reload;
input  [31:0] W_2_reload;
input  [31:0] W_3_reload;
input  [31:0] W_4_reload;
input  [31:0] W_5_reload;
input  [31:0] W_7_reload;
input  [31:0] W_8_reload;
input  [31:0] W_9_reload;
input  [31:0] W_10_reload;
input  [31:0] W_11_reload;
input  [31:0] W_12_reload;
input  [31:0] W_13_reload;
input  [31:0] W_15_reload;
input  [31:0] W_14_reload;
input  [31:0] W_6_reload;
input  [31:0] W_1_reload;

reg ap_idle;
reg w_strm_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln549_reg_790;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln549_fu_403_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    w_strm_blk_n;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] t_2_fu_108;
wire   [6:0] t_3_fu_570_p2;
wire    ap_loop_init;
reg   [31:0] empty_fu_112;
reg   [31:0] ap_sig_allocacmp_p_load38;
reg   [31:0] empty_86_fu_116;
reg   [31:0] empty_87_fu_120;
reg   [31:0] empty_88_fu_124;
reg   [31:0] empty_89_fu_128;
reg   [31:0] empty_90_fu_132;
reg   [31:0] empty_91_fu_136;
reg   [31:0] empty_92_fu_140;
reg   [31:0] empty_93_fu_144;
reg   [31:0] empty_94_fu_148;
reg   [31:0] empty_95_fu_152;
reg   [31:0] empty_96_fu_156;
reg   [31:0] empty_97_fu_160;
reg   [31:0] empty_98_fu_164;
reg   [31:0] empty_99_fu_168;
reg   [31:0] empty_100_fu_172;
wire   [31:0] Wt_fu_654_p2;
reg    ap_block_pp0_stage0_01001;
wire   [21:0] lshr_ln553_2_fu_446_p4;
wire   [28:0] lshr_ln553_5_fu_488_p4;
wire   [16:0] trunc_ln553_fu_428_p1;
wire   [14:0] lshr_ln_fu_418_p4;
wire   [18:0] trunc_ln553_1_fu_442_p1;
wire   [12:0] lshr_ln553_1_fu_432_p4;
wire   [6:0] trunc_ln553_2_fu_470_p1;
wire   [24:0] lshr_ln553_3_fu_460_p4;
wire   [17:0] trunc_ln553_3_fu_484_p1;
wire   [13:0] lshr_ln553_4_fu_474_p4;
wire   [31:0] or_ln_fu_502_p3;
wire   [31:0] zext_ln553_fu_456_p1;
wire   [31:0] xor_ln553_fu_534_p2;
wire   [31:0] or_ln553_1_fu_510_p3;
wire   [31:0] zext_ln553_1_fu_498_p1;
wire   [31:0] or_ln553_2_fu_518_p3;
wire   [31:0] xor_ln553_2_fu_546_p2;
wire   [31:0] or_ln553_3_fu_526_p3;
wire   [31:0] grp_fu_558_p1;
wire   [31:0] grp_fu_564_p0;
wire   [31:0] grp_fu_564_p2;
wire   [31:0] grp_fu_558_p2;
reg    grp_fu_558_ce;
reg    grp_fu_564_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 t_2_fu_108 = 7'd0;
#0 empty_fu_112 = 32'd0;
#0 empty_86_fu_116 = 32'd0;
#0 empty_87_fu_120 = 32'd0;
#0 empty_88_fu_124 = 32'd0;
#0 empty_89_fu_128 = 32'd0;
#0 empty_90_fu_132 = 32'd0;
#0 empty_91_fu_136 = 32'd0;
#0 empty_92_fu_140 = 32'd0;
#0 empty_93_fu_144 = 32'd0;
#0 empty_94_fu_148 = 32'd0;
#0 empty_95_fu_152 = 32'd0;
#0 empty_96_fu_156 = 32'd0;
#0 empty_97_fu_160 = 32'd0;
#0 empty_98_fu_164 = 32'd0;
#0 empty_99_fu_168 = 32'd0;
#0 empty_100_fu_172 = 32'd0;
#0 ap_done_reg = 1'b0;
end

test_hmac_sha256_add_32ns_32ns_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
add_32ns_32ns_32_2_1_U110(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_87_fu_120),
    .din1(grp_fu_558_p1),
    .ce(grp_fu_558_ce),
    .dout(grp_fu_558_p2)
);

test_hmac_sha256_add_32ns_32ns_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
add_32ns_32ns_32_2_1_U111(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_564_p0),
    .din1(empty_86_fu_116),
    .ce(grp_fu_564_ce),
    .dout(grp_fu_564_p2)
);

test_hmac_sha256_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
add_32ns_32ns_32_1_1_U112(
    .din0(grp_fu_564_p2),
    .din1(grp_fu_558_p2),
    .dout(Wt_fu_654_p2)
);

test_hmac_sha256_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_100_fu_172 <= W_reload;
        end else if (((icmp_ln549_reg_790 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            empty_100_fu_172 <= Wt_fu_654_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_86_fu_116 <= W_6_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_86_fu_116 <= empty_96_fu_156;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_87_fu_120 <= W_15_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_87_fu_120 <= empty_88_fu_124;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_88_fu_124 <= W_14_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_88_fu_124 <= empty_89_fu_128;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_89_fu_128 <= W_13_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_89_fu_128 <= empty_90_fu_132;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_90_fu_132 <= W_12_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_90_fu_132 <= empty_91_fu_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_91_fu_136 <= W_11_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_91_fu_136 <= empty_92_fu_140;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_92_fu_140 <= W_10_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_92_fu_140 <= empty_93_fu_144;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_93_fu_144 <= W_9_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_93_fu_144 <= empty_94_fu_148;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_94_fu_148 <= W_8_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_94_fu_148 <= empty_95_fu_152;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_95_fu_152 <= W_7_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_95_fu_152 <= empty_86_fu_116;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_96_fu_156 <= W_5_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_96_fu_156 <= empty_97_fu_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_97_fu_160 <= W_4_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_97_fu_160 <= empty_98_fu_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_98_fu_164 <= W_3_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_98_fu_164 <= empty_99_fu_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_99_fu_168 <= W_2_reload;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_99_fu_168 <= ap_sig_allocacmp_p_load38;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_fu_112 <= W_1_reload;
        end else if (((icmp_ln549_reg_790 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            empty_fu_112 <= empty_100_fu_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_2_fu_108 <= 7'd16;
        end else if (((icmp_ln549_fu_403_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            t_2_fu_108 <= t_3_fu_570_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln549_reg_790 <= icmp_ln549_fu_403_p2;
    end
end

always @ (*) begin
    if (((icmp_ln549_fu_403_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln549_reg_790 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_p_load38 = empty_100_fu_172;
    end else begin
        ap_sig_allocacmp_p_load38 = empty_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_558_ce = 1'b1;
    end else begin
        grp_fu_558_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_564_ce = 1'b1;
    end else begin
        grp_fu_564_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln549_reg_790 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_strm_blk_n = w_strm_full_n;
    end else begin
        w_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln549_reg_790 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_strm_write = 1'b1;
    end else begin
        w_strm_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln549_reg_790 == 1'd0) & (w_strm_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_558_p1 = (xor_ln553_2_fu_546_p2 ^ or_ln553_3_fu_526_p3);

assign grp_fu_564_p0 = (xor_ln553_fu_534_p2 ^ or_ln553_1_fu_510_p3);

assign icmp_ln549_fu_403_p2 = ((t_2_fu_108 == 7'd64) ? 1'b1 : 1'b0);

assign lshr_ln553_1_fu_432_p4 = {{ap_sig_allocacmp_p_load38[31:19]}};

assign lshr_ln553_2_fu_446_p4 = {{ap_sig_allocacmp_p_load38[31:10]}};

assign lshr_ln553_3_fu_460_p4 = {{empty_88_fu_124[31:7]}};

assign lshr_ln553_4_fu_474_p4 = {{empty_88_fu_124[31:18]}};

assign lshr_ln553_5_fu_488_p4 = {{empty_88_fu_124[31:3]}};

assign lshr_ln_fu_418_p4 = {{ap_sig_allocacmp_p_load38[31:17]}};

assign or_ln553_1_fu_510_p3 = {{trunc_ln553_1_fu_442_p1}, {lshr_ln553_1_fu_432_p4}};

assign or_ln553_2_fu_518_p3 = {{trunc_ln553_2_fu_470_p1}, {lshr_ln553_3_fu_460_p4}};

assign or_ln553_3_fu_526_p3 = {{trunc_ln553_3_fu_484_p1}, {lshr_ln553_4_fu_474_p4}};

assign or_ln_fu_502_p3 = {{trunc_ln553_fu_428_p1}, {lshr_ln_fu_418_p4}};

assign t_3_fu_570_p2 = (t_2_fu_108 + 7'd1);

assign trunc_ln553_1_fu_442_p1 = ap_sig_allocacmp_p_load38[18:0];

assign trunc_ln553_2_fu_470_p1 = empty_88_fu_124[6:0];

assign trunc_ln553_3_fu_484_p1 = empty_88_fu_124[17:0];

assign trunc_ln553_fu_428_p1 = ap_sig_allocacmp_p_load38[16:0];

assign w_strm_din = Wt_fu_654_p2;

assign xor_ln553_2_fu_546_p2 = (zext_ln553_1_fu_498_p1 ^ or_ln553_2_fu_518_p3);

assign xor_ln553_fu_534_p2 = (zext_ln553_fu_456_p1 ^ or_ln_fu_502_p3);

assign zext_ln553_1_fu_498_p1 = lshr_ln553_5_fu_488_p4;

assign zext_ln553_fu_456_p1 = lshr_ln553_2_fu_446_p4;

endmodule //test_hmac_sha256_generateMsgSchedule_Pipeline_LOOP_SHA256_PREPARE_WT64
