-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mergeKipadStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    mergeKipadStrm_empty_n : IN STD_LOGIC;
    mergeKipadStrm_read : OUT STD_LOGIC;
    mergeKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    mergeKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    blk_strm_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    blk_strm_full_n : IN STD_LOGIC;
    blk_strm_write : OUT STD_LOGIC;
    blk_strm_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    blk_strm_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (57 downto 0) );
end;


architecture behav of test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_pp0_stage9 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_pp0_stage10 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_pp0_stage11 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_pp0_stage12 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_pp0_stage13 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_pp0_stage14 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_pp0_stage15 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv58_0 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv58_1 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state19_pp0_stage2_iter1_grp16 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal grp_fu_125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage15 : signal is "none";
    signal icmp_ln101_reg_295 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state16_pp0_stage15_iter0_grp13 : BOOLEAN;
    signal ap_block_pp0_stage15_subdone : BOOLEAN;
    signal mergeKipadStrm_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_grp1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_grp2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_grp3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_grp4 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_grp5 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage8 : signal is "none";
    signal ap_block_pp0_stage8_grp6 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage9 : signal is "none";
    signal ap_block_pp0_stage9_grp7 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage10 : signal is "none";
    signal ap_block_pp0_stage10_grp8 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage11 : signal is "none";
    signal ap_block_pp0_stage11_grp9 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage12 : signal is "none";
    signal ap_block_pp0_stage12_grp10 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage13 : signal is "none";
    signal ap_block_pp0_stage13_grp11 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage14 : signal is "none";
    signal ap_block_pp0_stage14_grp12 : BOOLEAN;
    signal ap_block_pp0_stage15_grp13 : BOOLEAN;
    signal ap_block_pp0_stage0_grp14 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp15 : BOOLEAN;
    signal ap_block_pp0_stage2_grp16 : BOOLEAN;
    signal blk_strm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal grp_fu_130_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal j_2_reg_299 : STD_LOGIC_VECTOR (57 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal empty_fu_136_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_reg_304 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state4_pp0_stage3_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_grp1 : BOOLEAN;
    signal grp_fu_87_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_3_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_97_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_1_reg_314 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_107_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_2_reg_319 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_50_fu_144_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_50_reg_324 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state5_pp0_stage4_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp2 : BOOLEAN;
    signal p_4_reg_329 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_5_reg_334 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_6_reg_339 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_51_fu_148_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_51_reg_344 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state6_pp0_stage5_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage5_11001_grp3 : BOOLEAN;
    signal p_7_reg_349 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_8_reg_354 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_9_reg_359 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_52_fu_152_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_52_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state7_pp0_stage6_iter0_grp4 : BOOLEAN;
    signal ap_block_pp0_stage6_11001_grp4 : BOOLEAN;
    signal p_s_reg_369 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_10_reg_374 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_11_reg_379 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_53_fu_156_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_53_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state8_pp0_stage7_iter0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage7_11001_grp5 : BOOLEAN;
    signal p_12_reg_389 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_13_reg_394 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_14_reg_399 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_54_fu_160_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_54_reg_404 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state9_pp0_stage8_iter0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage8_11001_grp6 : BOOLEAN;
    signal p_15_reg_409 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_16_reg_414 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_17_reg_419 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_55_fu_164_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_55_reg_424 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state10_pp0_stage9_iter0_grp7 : BOOLEAN;
    signal ap_block_pp0_stage9_11001_grp7 : BOOLEAN;
    signal p_18_reg_429 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_19_reg_434 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_20_reg_439 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_56_fu_168_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_56_reg_444 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state11_pp0_stage10_iter0_grp8 : BOOLEAN;
    signal ap_block_pp0_stage10_11001_grp8 : BOOLEAN;
    signal p_21_reg_449 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_22_reg_454 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_23_reg_459 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_57_fu_172_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_57_reg_464 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state12_pp0_stage11_iter0_grp9 : BOOLEAN;
    signal ap_block_pp0_stage11_11001_grp9 : BOOLEAN;
    signal p_24_reg_469 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_25_reg_474 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_26_reg_479 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_58_fu_176_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_58_reg_484 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state13_pp0_stage12_iter0_grp10 : BOOLEAN;
    signal ap_block_pp0_stage12_11001_grp10 : BOOLEAN;
    signal p_27_reg_489 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_28_reg_494 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_29_reg_499 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_59_fu_180_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_59_reg_504 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state14_pp0_stage13_iter0_grp11 : BOOLEAN;
    signal ap_block_pp0_stage13_11001_grp11 : BOOLEAN;
    signal p_30_reg_509 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_31_reg_514 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_32_reg_519 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_60_fu_184_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_60_reg_524 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state15_pp0_stage14_iter0_grp12 : BOOLEAN;
    signal ap_block_pp0_stage14_11001_grp12 : BOOLEAN;
    signal p_33_reg_529 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_34_reg_534 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_35_reg_539 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_61_fu_188_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_61_reg_544 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage15_11001_grp13 : BOOLEAN;
    signal p_36_reg_549 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_37_reg_554 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_38_reg_559 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_62_fu_192_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_62_reg_564 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp14 : BOOLEAN;
    signal p_39_reg_569 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_40_reg_574 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_41_reg_579 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_63_fu_196_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_63_reg_584 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001_grp15 : BOOLEAN;
    signal p_42_reg_589 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_43_reg_594 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_44_reg_599 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_fu_64 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    signal ap_block_pp0_stage3_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp16 : BOOLEAN;
    signal ap_block_pp0_stage2_01001_grp16 : BOOLEAN;
    signal empty_64_fu_200_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_125_ce : STD_LOGIC;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_00001_grp0 : BOOLEAN;
    signal grp_fu_130_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_block_pp0_stage9_subdone : BOOLEAN;
    signal ap_block_pp0_stage10_subdone : BOOLEAN;
    signal ap_block_pp0_stage11_subdone : BOOLEAN;
    signal ap_block_pp0_stage12_subdone : BOOLEAN;
    signal ap_block_pp0_stage13_subdone : BOOLEAN;
    signal ap_block_pp0_stage14_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_hmac_sha256_icmp_58ns_58ns_1_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        OP_CODE : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (57 downto 0);
        din1 : IN STD_LOGIC_VECTOR (57 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component test_hmac_sha256_add_58ns_58ns_58_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (57 downto 0);
        din1 : IN STD_LOGIC_VECTOR (57 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component test_hmac_sha256_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    icmp_58ns_58ns_1_2_1_U30 : component test_hmac_sha256_icmp_58ns_58ns_1_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 58,
        din1_WIDTH => 58,
        OP_CODE => 0,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => j_fu_64,
        din1 => trunc_ln,
        ce => grp_fu_125_ce,
        dout => grp_fu_125_p2);

    add_58ns_58ns_58_2_1_U31 : component test_hmac_sha256_add_58ns_58ns_58_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 58,
        din1_WIDTH => 58,
        dout_WIDTH => 58)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => j_fu_64,
        din1 => ap_const_lv58_1,
        ce => grp_fu_130_ce,
        dout => grp_fu_130_p2);

    flow_control_loop_pipe_sequential_init_U : component test_hmac_sha256_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage15_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    j_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_64 <= ap_const_lv58_0;
            elsif (((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                j_fu_64 <= j_2_reg_299;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                empty_50_reg_324 <= empty_50_fu_144_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                empty_51_reg_344 <= empty_51_fu_148_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                empty_52_reg_364 <= empty_52_fu_152_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                empty_53_reg_384 <= empty_53_fu_156_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage8_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then
                empty_54_reg_404 <= empty_54_fu_160_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage9_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9))) then
                empty_55_reg_424 <= empty_55_fu_164_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage10_11001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10))) then
                empty_56_reg_444 <= empty_56_fu_168_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage11_11001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11))) then
                empty_57_reg_464 <= empty_57_fu_172_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then
                empty_58_reg_484 <= empty_58_fu_176_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage13_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13))) then
                empty_59_reg_504 <= empty_59_fu_180_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage14_11001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14))) then
                empty_60_reg_524 <= empty_60_fu_184_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage15_11001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then
                empty_61_reg_544 <= empty_61_fu_188_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp14) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_62_reg_564 <= empty_62_fu_192_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp15) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                empty_63_reg_584 <= empty_63_fu_196_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                empty_reg_304 <= empty_fu_136_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                icmp_ln101_reg_295 <= grp_fu_125_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                j_2_reg_299 <= grp_fu_130_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                p_10_reg_374 <= mergeKipadStrm_dout(15 downto 8);
                p_11_reg_379 <= mergeKipadStrm_dout(23 downto 16);
                p_s_reg_369 <= mergeKipadStrm_dout(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                p_12_reg_389 <= mergeKipadStrm_dout(31 downto 24);
                p_13_reg_394 <= mergeKipadStrm_dout(15 downto 8);
                p_14_reg_399 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then
                p_15_reg_409 <= mergeKipadStrm_dout(31 downto 24);
                p_16_reg_414 <= mergeKipadStrm_dout(15 downto 8);
                p_17_reg_419 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9))) then
                p_18_reg_429 <= mergeKipadStrm_dout(31 downto 24);
                p_19_reg_434 <= mergeKipadStrm_dout(15 downto 8);
                p_20_reg_439 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                p_1_reg_314 <= mergeKipadStrm_dout(15 downto 8);
                p_2_reg_319 <= mergeKipadStrm_dout(23 downto 16);
                p_3_reg_309 <= mergeKipadStrm_dout(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_11001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10))) then
                p_21_reg_449 <= mergeKipadStrm_dout(31 downto 24);
                p_22_reg_454 <= mergeKipadStrm_dout(15 downto 8);
                p_23_reg_459 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_11001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11))) then
                p_24_reg_469 <= mergeKipadStrm_dout(31 downto 24);
                p_25_reg_474 <= mergeKipadStrm_dout(15 downto 8);
                p_26_reg_479 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then
                p_27_reg_489 <= mergeKipadStrm_dout(31 downto 24);
                p_28_reg_494 <= mergeKipadStrm_dout(15 downto 8);
                p_29_reg_499 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13))) then
                p_30_reg_509 <= mergeKipadStrm_dout(31 downto 24);
                p_31_reg_514 <= mergeKipadStrm_dout(15 downto 8);
                p_32_reg_519 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_11001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14))) then
                p_33_reg_529 <= mergeKipadStrm_dout(31 downto 24);
                p_34_reg_534 <= mergeKipadStrm_dout(15 downto 8);
                p_35_reg_539 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_11001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then
                p_36_reg_549 <= mergeKipadStrm_dout(31 downto 24);
                p_37_reg_554 <= mergeKipadStrm_dout(15 downto 8);
                p_38_reg_559 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_39_reg_569 <= mergeKipadStrm_dout(31 downto 24);
                p_40_reg_574 <= mergeKipadStrm_dout(15 downto 8);
                p_41_reg_579 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_42_reg_589 <= mergeKipadStrm_dout(31 downto 24);
                p_43_reg_594 <= mergeKipadStrm_dout(15 downto 8);
                p_44_reg_599 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                p_4_reg_329 <= mergeKipadStrm_dout(31 downto 24);
                p_5_reg_334 <= mergeKipadStrm_dout(15 downto 8);
                p_6_reg_339 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                p_7_reg_349 <= mergeKipadStrm_dout(31 downto 24);
                p_8_reg_354 <= mergeKipadStrm_dout(15 downto 8);
                p_9_reg_359 <= mergeKipadStrm_dout(23 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage15_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage3_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_block_pp0_stage8_subdone, ap_block_pp0_stage9_subdone, ap_block_pp0_stage10_subdone, ap_block_pp0_stage11_subdone, ap_block_pp0_stage12_subdone, ap_block_pp0_stage13_subdone, ap_block_pp0_stage14_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when ap_ST_fsm_pp0_stage9 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage9_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                end if;
            when ap_ST_fsm_pp0_stage10 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage10_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                end if;
            when ap_ST_fsm_pp0_stage11 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage11_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                end if;
            when ap_ST_fsm_pp0_stage12 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage12_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage13;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                end if;
            when ap_ST_fsm_pp0_stage13 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage13_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage14;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage13;
                end if;
            when ap_ST_fsm_pp0_stage14 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage14_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage14;
                end if;
            when ap_ST_fsm_pp0_stage15 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage15_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage15;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage10 <= ap_CS_fsm(10);
    ap_CS_fsm_pp0_stage11 <= ap_CS_fsm(11);
    ap_CS_fsm_pp0_stage12 <= ap_CS_fsm(12);
    ap_CS_fsm_pp0_stage13 <= ap_CS_fsm(13);
    ap_CS_fsm_pp0_stage14 <= ap_CS_fsm(14);
    ap_CS_fsm_pp0_stage15 <= ap_CS_fsm(15);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
    ap_CS_fsm_pp0_stage8 <= ap_CS_fsm(8);
    ap_CS_fsm_pp0_stage9 <= ap_CS_fsm(9);
        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp14_assign_proc : process(ap_enable_reg_pp0_iter1, mergeKipadStrm_empty_n)
    begin
                ap_block_pp0_stage0_11001_grp14 <= ((mergeKipadStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp14 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, mergeKipadStrm_empty_n)
    begin
                ap_block_pp0_stage0_subdone <= ((mergeKipadStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage10_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp8)
    begin
                ap_block_pp0_stage10_11001_grp8 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp8));
    end process;

        ap_block_pp0_stage10_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage10_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp8)
    begin
                ap_block_pp0_stage10_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp8));
    end process;


    ap_block_pp0_stage11_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp9)
    begin
                ap_block_pp0_stage11_11001_grp9 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp9));
    end process;

        ap_block_pp0_stage11_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage11_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp9)
    begin
                ap_block_pp0_stage11_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp9));
    end process;


    ap_block_pp0_stage12_11001_grp10_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp10)
    begin
                ap_block_pp0_stage12_11001_grp10 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp10));
    end process;

        ap_block_pp0_stage12_grp10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage12_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp10)
    begin
                ap_block_pp0_stage12_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp10));
    end process;


    ap_block_pp0_stage13_11001_grp11_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp11)
    begin
                ap_block_pp0_stage13_11001_grp11 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp11));
    end process;

        ap_block_pp0_stage13_grp11 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage13_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp11)
    begin
                ap_block_pp0_stage13_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp11));
    end process;


    ap_block_pp0_stage14_11001_grp12_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp12)
    begin
                ap_block_pp0_stage14_11001_grp12 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp12));
    end process;

        ap_block_pp0_stage14_grp12 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage14_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp12)
    begin
                ap_block_pp0_stage14_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp12));
    end process;


    ap_block_pp0_stage15_11001_grp13_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp13)
    begin
                ap_block_pp0_stage15_11001_grp13 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp13));
    end process;

        ap_block_pp0_stage15_grp13 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage15_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp13)
    begin
                ap_block_pp0_stage15_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp13));
    end process;

        ap_block_pp0_stage1_00001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, mergeKipadStrm_empty_n)
    begin
                ap_block_pp0_stage1_11001 <= ((mergeKipadStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp15_assign_proc : process(ap_enable_reg_pp0_iter1, mergeKipadStrm_empty_n)
    begin
                ap_block_pp0_stage1_11001_grp15 <= ((mergeKipadStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp15 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, mergeKipadStrm_empty_n)
    begin
                ap_block_pp0_stage1_subdone <= ((mergeKipadStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state19_pp0_stage2_iter1_grp16)
    begin
                ap_block_pp0_stage2_01001_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage2_iter1_grp16));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state19_pp0_stage2_iter1_grp16)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage2_iter1_grp16));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state19_pp0_stage2_iter1_grp16)
    begin
                ap_block_pp0_stage2_11001_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage2_iter1_grp16));
    end process;

        ap_block_pp0_stage2_grp16 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state19_pp0_stage2_iter1_grp16)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage2_iter1_grp16));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp1)
    begin
                ap_block_pp0_stage3_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp1));
    end process;

        ap_block_pp0_stage3_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp1)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp1));
    end process;

        ap_block_pp0_stage3_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp2)
    begin
                ap_block_pp0_stage4_11001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp2));
    end process;

        ap_block_pp0_stage4_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp2)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp2));
    end process;


    ap_block_pp0_stage5_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp3)
    begin
                ap_block_pp0_stage5_11001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp3));
    end process;

        ap_block_pp0_stage5_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp3)
    begin
                ap_block_pp0_stage5_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp3));
    end process;


    ap_block_pp0_stage6_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp4)
    begin
                ap_block_pp0_stage6_11001_grp4 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp4));
    end process;

        ap_block_pp0_stage6_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp4)
    begin
                ap_block_pp0_stage6_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp4));
    end process;


    ap_block_pp0_stage7_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp5)
    begin
                ap_block_pp0_stage7_11001_grp5 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp5));
    end process;

        ap_block_pp0_stage7_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp5)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp5));
    end process;


    ap_block_pp0_stage8_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp6)
    begin
                ap_block_pp0_stage8_11001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp6));
    end process;

        ap_block_pp0_stage8_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage8_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp6)
    begin
                ap_block_pp0_stage8_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp6));
    end process;


    ap_block_pp0_stage9_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp7)
    begin
                ap_block_pp0_stage9_11001_grp7 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp7));
    end process;

        ap_block_pp0_stage9_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage9_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp7)
    begin
                ap_block_pp0_stage9_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp7));
    end process;


    ap_block_state10_pp0_stage9_iter0_grp7_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state10_pp0_stage9_iter0_grp7 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state11_pp0_stage10_iter0_grp8_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state11_pp0_stage10_iter0_grp8 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state12_pp0_stage11_iter0_grp9_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state12_pp0_stage11_iter0_grp9 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state13_pp0_stage12_iter0_grp10_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state13_pp0_stage12_iter0_grp10 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state14_pp0_stage13_iter0_grp11_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state14_pp0_stage13_iter0_grp11 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state15_pp0_stage14_iter0_grp12_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state15_pp0_stage14_iter0_grp12 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state16_pp0_stage15_iter0_grp13_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state16_pp0_stage15_iter0_grp13 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state19_pp0_stage2_iter1_grp16_assign_proc : process(mergeKipadStrm_empty_n, blk_strm_full_n)
    begin
                ap_block_state19_pp0_stage2_iter1_grp16 <= ((blk_strm_full_n = ap_const_logic_0) or (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp1_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state4_pp0_stage3_iter0_grp1 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp2_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state5_pp0_stage4_iter0_grp2 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state6_pp0_stage5_iter0_grp3_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state6_pp0_stage5_iter0_grp3 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state7_pp0_stage6_iter0_grp4_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state7_pp0_stage6_iter0_grp4 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state8_pp0_stage7_iter0_grp5_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state8_pp0_stage7_iter0_grp5 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage8_iter0_grp6_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln101_reg_295)
    begin
                ap_block_state9_pp0_stage8_iter0_grp6 <= ((icmp_ln101_reg_295 = ap_const_lv1_0) and (mergeKipadStrm_empty_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, grp_fu_125_p2)
    begin
        if (((grp_fu_125_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, ap_block_pp0_stage15_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    blk_strm_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, blk_strm_full_n, ap_block_pp0_stage2_grp16)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            blk_strm_blk_n <= blk_strm_full_n;
        else 
            blk_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    blk_strm_din <= (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((empty_64_fu_200_p1 & grp_fu_97_p4) & grp_fu_107_p4) & grp_fu_87_p4) & empty_63_reg_584) & p_43_reg_594) & p_44_reg_599) & p_42_reg_589) & empty_62_reg_564) & p_40_reg_574) & p_41_reg_579) & p_39_reg_569) & empty_61_reg_544) & p_37_reg_554) & p_38_reg_559) & p_36_reg_549) & empty_60_reg_524) & p_34_reg_534) & p_35_reg_539) & p_33_reg_529) & empty_59_reg_504) & p_31_reg_514) & p_32_reg_519) & p_30_reg_509) & empty_58_reg_484) & p_28_reg_494) & p_29_reg_499) & p_27_reg_489) & empty_57_reg_464) & p_25_reg_474) & p_26_reg_479) & p_24_reg_469) & empty_56_reg_444) & p_22_reg_454) & p_23_reg_459) & p_21_reg_449) & empty_55_reg_424) & p_19_reg_434) & p_20_reg_439) & p_18_reg_429) & empty_54_reg_404) & p_16_reg_414) & p_17_reg_419) & p_15_reg_409) & empty_53_reg_384) & p_13_reg_394) & p_14_reg_399) & p_12_reg_389) & empty_52_reg_364) & p_10_reg_374) & p_11_reg_379) & p_s_reg_369) & empty_51_reg_344) & p_8_reg_354) & p_9_reg_359) & p_7_reg_349) & empty_50_reg_324) 
    & p_5_reg_334) & p_6_reg_339) & p_4_reg_329) & empty_reg_304) & p_1_reg_314) & p_2_reg_319) & p_3_reg_309);

    blk_strm_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001_grp16)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            blk_strm_write <= ap_const_logic_1;
        else 
            blk_strm_write <= ap_const_logic_0;
        end if; 
    end process;

    empty_50_fu_144_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_51_fu_148_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_52_fu_152_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_53_fu_156_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_54_fu_160_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_55_fu_164_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_56_fu_168_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_57_fu_172_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_58_fu_176_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_59_fu_180_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_60_fu_184_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_61_fu_188_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_62_fu_192_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_63_fu_196_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_64_fu_200_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    empty_fu_136_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    grp_fu_107_p4 <= mergeKipadStrm_dout(23 downto 16);

    grp_fu_125_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_125_ce <= ap_const_logic_1;
        else 
            grp_fu_125_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_130_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_130_ce <= ap_const_logic_1;
        else 
            grp_fu_130_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_87_p4 <= mergeKipadStrm_dout(31 downto 24);
    grp_fu_97_p4 <= mergeKipadStrm_dout(15 downto 8);

    mergeKipadStrm_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, mergeKipadStrm_empty_n, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln101_reg_295, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp1, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp2, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_grp3, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_grp4, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_grp5, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_grp6, ap_CS_fsm_pp0_stage9, ap_block_pp0_stage9_grp7, ap_CS_fsm_pp0_stage10, ap_block_pp0_stage10_grp8, ap_CS_fsm_pp0_stage11, ap_block_pp0_stage11_grp9, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage12_grp10, ap_CS_fsm_pp0_stage13, ap_block_pp0_stage13_grp11, ap_CS_fsm_pp0_stage14, ap_block_pp0_stage14_grp12, ap_block_pp0_stage15_grp13, ap_block_pp0_stage0_grp14, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp15, ap_block_pp0_stage2_grp16)
    begin
        if ((((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and 
    (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and 
    (ap_const_boolean_0 = ap_block_pp0_stage5_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_grp14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            mergeKipadStrm_blk_n <= mergeKipadStrm_empty_n;
        else 
            mergeKipadStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mergeKipadStrm_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln101_reg_295, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage9, ap_CS_fsm_pp0_stage10, ap_CS_fsm_pp0_stage11, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage13, ap_CS_fsm_pp0_stage14, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage3_11001_grp1, ap_block_pp0_stage4_11001_grp2, ap_block_pp0_stage5_11001_grp3, ap_block_pp0_stage6_11001_grp4, ap_block_pp0_stage7_11001_grp5, ap_block_pp0_stage8_11001_grp6, ap_block_pp0_stage9_11001_grp7, ap_block_pp0_stage10_11001_grp8, ap_block_pp0_stage11_11001_grp9, ap_block_pp0_stage12_11001_grp10, ap_block_pp0_stage13_11001_grp11, ap_block_pp0_stage14_11001_grp12, ap_block_pp0_stage15_11001_grp13, ap_block_pp0_stage0_11001_grp14, ap_block_pp0_stage1_11001_grp15, ap_block_pp0_stage2_11001_grp16)
    begin
        if ((((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_11001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_11001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_11001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11)) or ((icmp_ln101_reg_295 
    = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_11001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg 
    = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((icmp_ln101_reg_295 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            mergeKipadStrm_read <= ap_const_logic_1;
        else 
            mergeKipadStrm_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
