// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_sha256Digest_256_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        nblk_strm2_dout,
        nblk_strm2_empty_n,
        nblk_strm2_read,
        nblk_strm2_num_data_valid,
        nblk_strm2_fifo_cap,
        end_nblk_strm2_dout,
        end_nblk_strm2_empty_n,
        end_nblk_strm2_read,
        end_nblk_strm2_num_data_valid,
        end_nblk_strm2_fifo_cap,
        w_strm_dout,
        w_strm_empty_n,
        w_strm_read,
        w_strm_num_data_valid,
        w_strm_fifo_cap,
        msgHashStrm_din,
        msgHashStrm_full_n,
        msgHashStrm_write,
        msgHashStrm_num_data_valid,
        msgHashStrm_fifo_cap,
        eMsgHashStrm_din,
        eMsgHashStrm_full_n,
        eMsgHashStrm_write,
        eMsgHashStrm_num_data_valid,
        eMsgHashStrm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] nblk_strm2_dout;
input   nblk_strm2_empty_n;
output   nblk_strm2_read;
input  [5:0] nblk_strm2_num_data_valid;
input  [5:0] nblk_strm2_fifo_cap;
input  [0:0] end_nblk_strm2_dout;
input   end_nblk_strm2_empty_n;
output   end_nblk_strm2_read;
input  [5:0] end_nblk_strm2_num_data_valid;
input  [5:0] end_nblk_strm2_fifo_cap;
input  [31:0] w_strm_dout;
input   w_strm_empty_n;
output   w_strm_read;
input  [5:0] w_strm_num_data_valid;
input  [5:0] w_strm_fifo_cap;
output  [255:0] msgHashStrm_din;
input   msgHashStrm_full_n;
output   msgHashStrm_write;
input  [2:0] msgHashStrm_num_data_valid;
input  [2:0] msgHashStrm_fifo_cap;
output  [0:0] eMsgHashStrm_din;
input   eMsgHashStrm_full_n;
output   eMsgHashStrm_write;
input  [2:0] eMsgHashStrm_num_data_valid;
input  [2:0] eMsgHashStrm_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg nblk_strm2_read;
reg end_nblk_strm2_read;
reg msgHashStrm_write;
reg[0:0] eMsgHashStrm_din;
reg eMsgHashStrm_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    nblk_strm2_blk_n;
wire    ap_CS_fsm_state2;
reg    end_nblk_strm2_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln663_fu_302_p2;
reg    msgHashStrm_blk_n;
reg    eMsgHashStrm_blk_n;
reg    ap_block_state1;
reg   [63:0] blk_num_reg_731;
reg    ap_block_state2;
wire   [63:0] n_1_fu_307_p2;
reg   [63:0] n_1_reg_739;
reg    ap_block_state3;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_done;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_idle;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_ready;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_w_strm_read;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6888_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6888_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6897_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6897_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6906_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6906_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6915_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6915_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6924_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6924_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6933_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6933_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6942_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6942_out_ap_vld;
wire   [31:0] grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6951_out;
wire    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6951_out_ap_vld;
reg   [0:0] end_flag_1_reg_156;
reg   [31:0] h_reg_165;
wire    ap_CS_fsm_state5;
reg   [31:0] g_reg_177;
reg   [31:0] f_reg_189;
reg   [31:0] e_reg_201;
reg   [31:0] d_reg_213;
reg   [31:0] c_reg_225;
reg   [31:0] b_reg_237;
reg   [31:0] a_reg_249;
reg   [63:0] n_reg_261;
reg    grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start_reg;
reg    ap_block_state3_ignore_call3;
wire    ap_CS_fsm_state4;
wire   [7:0] t3_7_fu_561_p1;
wire   [7:0] trunc_ln727_5_fu_575_p4;
wire   [7:0] tmp_7_fu_565_p4;
wire   [7:0] t0_7_fu_551_p4;
wire   [7:0] t3_6_fu_527_p1;
wire   [7:0] trunc_ln727_4_fu_541_p4;
wire   [7:0] tmp_6_fu_531_p4;
wire   [7:0] t0_6_fu_517_p4;
wire   [7:0] t3_5_fu_493_p1;
wire   [7:0] trunc_ln727_3_fu_507_p4;
wire   [7:0] tmp_5_fu_497_p4;
wire   [7:0] t0_5_fu_483_p4;
wire   [7:0] t3_4_fu_459_p1;
wire   [7:0] trunc_ln727_2_fu_473_p4;
wire   [7:0] tmp_4_fu_463_p4;
wire   [7:0] t0_4_fu_449_p4;
wire   [7:0] t3_3_fu_425_p1;
wire   [7:0] trunc_ln727_1_fu_439_p4;
wire   [7:0] tmp_3_fu_429_p4;
wire   [7:0] t0_3_fu_415_p4;
wire   [7:0] t3_2_fu_391_p1;
wire   [7:0] trunc_ln727_s_fu_405_p4;
wire   [7:0] tmp_2_fu_395_p4;
wire   [7:0] t0_2_fu_381_p4;
wire   [7:0] t3_1_fu_357_p1;
wire   [7:0] trunc_ln727_9_fu_371_p4;
wire   [7:0] tmp_1_fu_361_p4;
wire   [7:0] t0_1_fu_347_p4;
wire   [7:0] t3_fu_323_p1;
wire   [7:0] trunc_ln727_8_fu_337_p4;
wire   [7:0] tmp_fu_327_p4;
wire   [7:0] t0_fu_313_p4;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start_reg = 1'b0;
end

test_hmac_sha256_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start),
    .ap_done(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_done),
    .ap_idle(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_idle),
    .ap_ready(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_ready),
    .w_strm_dout(w_strm_dout),
    .w_strm_empty_n(w_strm_empty_n),
    .w_strm_read(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_w_strm_read),
    .w_strm_num_data_valid(6'd0),
    .w_strm_fifo_cap(6'd0),
    .h(h_reg_165),
    .g(g_reg_177),
    .f(f_reg_189),
    .e(e_reg_201),
    .d(d_reg_213),
    .c(c_reg_225),
    .b(b_reg_237),
    .a(a_reg_249),
    .add_ln6888_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6888_out),
    .add_ln6888_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6888_out_ap_vld),
    .add_ln6897_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6897_out),
    .add_ln6897_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6897_out_ap_vld),
    .add_ln6906_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6906_out),
    .add_ln6906_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6906_out_ap_vld),
    .add_ln6915_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6915_out),
    .add_ln6915_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6915_out_ap_vld),
    .add_ln6924_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6924_out),
    .add_ln6924_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6924_out_ap_vld),
    .add_ln6933_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6933_out),
    .add_ln6933_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6933_out_ap_vld),
    .add_ln6942_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6942_out),
    .add_ln6942_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6942_out_ap_vld),
    .add_ln6951_out(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6951_out),
    .add_ln6951_out_ap_vld(grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6951_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state3_ignore_call3) & (icmp_ln663_fu_302_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start_reg <= 1'b1;
        end else if ((grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_ready == 1'b1)) begin
            grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        a_reg_249 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6888_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        a_reg_249 <= 32'd1779033703;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        b_reg_237 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6897_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_reg_237 <= 32'd3144134277;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        c_reg_225 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6906_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        c_reg_225 <= 32'd1013904242;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        d_reg_213 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6915_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        d_reg_213 <= 32'd2773480762;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        e_reg_201 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6924_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        e_reg_201 <= 32'd1359893119;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        f_reg_189 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6933_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        f_reg_189 <= 32'd2600822924;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        g_reg_177 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6942_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        g_reg_177 <= 32'd528734635;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        h_reg_165 <= grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_add_ln6951_out;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        h_reg_165 <= 32'd1541459225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        n_reg_261 <= n_1_reg_739;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        n_reg_261 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        blk_num_reg_731 <= nblk_strm2_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        end_flag_1_reg_156 <= end_nblk_strm2_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        n_1_reg_739 <= n_1_fu_307_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        eMsgHashStrm_blk_n = eMsgHashStrm_full_n;
    end else begin
        eMsgHashStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        eMsgHashStrm_din = 1'd0;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        eMsgHashStrm_din = 1'd1;
    end else begin
        eMsgHashStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        eMsgHashStrm_write = 1'b1;
    end else begin
        eMsgHashStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        end_nblk_strm2_blk_n = end_nblk_strm2_empty_n;
    end else begin
        end_nblk_strm2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        end_nblk_strm2_read = 1'b1;
    end else begin
        end_nblk_strm2_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        msgHashStrm_blk_n = msgHashStrm_full_n;
    end else begin
        msgHashStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        msgHashStrm_write = 1'b1;
    end else begin
        msgHashStrm_write = 1'b0;
    end
end

always @ (*) begin
    if (((end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        nblk_strm2_blk_n = nblk_strm2_empty_n;
    end else begin
        nblk_strm2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        nblk_strm2_read = 1'b1;
    end else begin
        nblk_strm2_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_156 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b0 == ap_block_state3) & (icmp_ln663_fu_302_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((end_nblk_strm2_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = (((end_flag_1_reg_156 == 1'd1) & (eMsgHashStrm_full_n == 1'b0)) | ((end_flag_1_reg_156 == 1'd0) & (nblk_strm2_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3 = (((icmp_ln663_fu_302_p2 == 1'd1) & (end_nblk_strm2_empty_n == 1'b0)) | ((icmp_ln663_fu_302_p2 == 1'd1) & (msgHashStrm_full_n == 1'b0)) | ((icmp_ln663_fu_302_p2 == 1'd1) & (eMsgHashStrm_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_ignore_call3 = (((icmp_ln663_fu_302_p2 == 1'd1) & (end_nblk_strm2_empty_n == 1'b0)) | ((icmp_ln663_fu_302_p2 == 1'd1) & (msgHashStrm_full_n == 1'b0)) | ((icmp_ln663_fu_302_p2 == 1'd1) & (eMsgHashStrm_full_n == 1'b0)));
end

assign grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start = grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_ap_start_reg;

assign icmp_ln663_fu_302_p2 = ((n_reg_261 == blk_num_reg_731) ? 1'b1 : 1'b0);

assign msgHashStrm_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{t3_7_fu_561_p1}, {trunc_ln727_5_fu_575_p4}}, {tmp_7_fu_565_p4}}, {t0_7_fu_551_p4}}, {t3_6_fu_527_p1}}, {trunc_ln727_4_fu_541_p4}}, {tmp_6_fu_531_p4}}, {t0_6_fu_517_p4}}, {t3_5_fu_493_p1}}, {trunc_ln727_3_fu_507_p4}}, {tmp_5_fu_497_p4}}, {t0_5_fu_483_p4}}, {t3_4_fu_459_p1}}, {trunc_ln727_2_fu_473_p4}}, {tmp_4_fu_463_p4}}, {t0_4_fu_449_p4}}, {t3_3_fu_425_p1}}, {trunc_ln727_1_fu_439_p4}}, {tmp_3_fu_429_p4}}, {t0_3_fu_415_p4}}, {t3_2_fu_391_p1}}, {trunc_ln727_s_fu_405_p4}}, {tmp_2_fu_395_p4}}, {t0_2_fu_381_p4}}, {t3_1_fu_357_p1}}, {trunc_ln727_9_fu_371_p4}}, {tmp_1_fu_361_p4}}, {t0_1_fu_347_p4}}, {t3_fu_323_p1}}, {trunc_ln727_8_fu_337_p4}}, {tmp_fu_327_p4}}, {t0_fu_313_p4}};

assign n_1_fu_307_p2 = (n_reg_261 + 64'd1);

assign t0_1_fu_347_p4 = {{b_reg_237[31:24]}};

assign t0_2_fu_381_p4 = {{c_reg_225[31:24]}};

assign t0_3_fu_415_p4 = {{d_reg_213[31:24]}};

assign t0_4_fu_449_p4 = {{e_reg_201[31:24]}};

assign t0_5_fu_483_p4 = {{f_reg_189[31:24]}};

assign t0_6_fu_517_p4 = {{g_reg_177[31:24]}};

assign t0_7_fu_551_p4 = {{h_reg_165[31:24]}};

assign t0_fu_313_p4 = {{a_reg_249[31:24]}};

assign t3_1_fu_357_p1 = b_reg_237[7:0];

assign t3_2_fu_391_p1 = c_reg_225[7:0];

assign t3_3_fu_425_p1 = d_reg_213[7:0];

assign t3_4_fu_459_p1 = e_reg_201[7:0];

assign t3_5_fu_493_p1 = f_reg_189[7:0];

assign t3_6_fu_527_p1 = g_reg_177[7:0];

assign t3_7_fu_561_p1 = h_reg_165[7:0];

assign t3_fu_323_p1 = a_reg_249[7:0];

assign tmp_1_fu_361_p4 = {{b_reg_237[23:16]}};

assign tmp_2_fu_395_p4 = {{c_reg_225[23:16]}};

assign tmp_3_fu_429_p4 = {{d_reg_213[23:16]}};

assign tmp_4_fu_463_p4 = {{e_reg_201[23:16]}};

assign tmp_5_fu_497_p4 = {{f_reg_189[23:16]}};

assign tmp_6_fu_531_p4 = {{g_reg_177[23:16]}};

assign tmp_7_fu_565_p4 = {{h_reg_165[23:16]}};

assign tmp_fu_327_p4 = {{a_reg_249[23:16]}};

assign trunc_ln727_1_fu_439_p4 = {{d_reg_213[15:8]}};

assign trunc_ln727_2_fu_473_p4 = {{e_reg_201[15:8]}};

assign trunc_ln727_3_fu_507_p4 = {{f_reg_189[15:8]}};

assign trunc_ln727_4_fu_541_p4 = {{g_reg_177[15:8]}};

assign trunc_ln727_5_fu_575_p4 = {{h_reg_165[15:8]}};

assign trunc_ln727_8_fu_337_p4 = {{a_reg_249[15:8]}};

assign trunc_ln727_9_fu_371_p4 = {{b_reg_237[15:8]}};

assign trunc_ln727_s_fu_405_p4 = {{c_reg_225[15:8]}};

assign w_strm_read = grp_sha256Digest_256_Pipeline_LOOP_SHA256_UPDATE_64_ROUNDS_fu_272_w_strm_read;

endmodule //test_hmac_sha256_sha256Digest_256_s
